### ISSUE TITLE
Vote extension: SignAndCheckVote broken [0.38.0-rc1]

### ISSUE THREAD

**Issue by alpe** [cometbft/cometbft#1001]
## Bug Report
I keep running into `extensions must be present IFF vote is a non-nil Precommit` errors in my wasmd tests, although the vote type, extension and block height is set to valid data. Even with modified code and extension=false in `types.MakeCommit`, I end up with the error. 

When I looked into [types.SignAndCheckVote](https://github.com/cometbft/cometbft/blob/v0.38.0-rc1/types/vote.go#L419-L420), I noticed:
* `extSignature := (len(v.ExtensionSignature) > 0)` is used, although it should be `v.Extension` from what I see
* the `extSignature == (!isPrecommit || isNil) ` condition always fails with `Extension` set, non 0 block and pre-commit vote
* I was wondering if the extension is optional in the genesis block, anyway? Where can i find some doc about this?
* `types.MakeCommit` does not add any optional `Extension` data to the vote. How is this supposed to work?

I was using Comet-BFT 0.38.0-rc1, with sdk v0.50.alpha.0, notionals ibc-go fork and an integration branch in [wasmd](https://github.com/CosmWasm/wasmd/pull/1448)

**Comment by sergio-mena** [comment]
Hello, we have several questions to the submitter
* We need more data to better see what is going on, ideally
  * The full log message(s) you get (`extensions must be present IFF vote is a non-nil Precommit`), with the actual values reported
  * Your program's stack trace at the moment this problem is hit
* The condition `extSignature == (!isPrecommit || isNil)` is what was intended (not `Extension`). If everything is good, the call to `privVal.SignVote` should have produced a non-empty extension signature
* Branch `v0.38.x` does not have  a `types.MakeCommit` function. There is a function `MakeCommit` inside `internal/test` but this one should only be used for internal unit tests _within_ CometBFT, it is not intended for external use. Is that the one you are using?

**Comment by alpe** [comment]
Thank you for your fast response!
it was referring to [`MakeExtCommit`](https://github.com/cometbft/cometbft/blob/v0.38.0-rc1/types/test_util.go#L14) and not `MakeCommit` indeed. Sorry for the confusion. It was late after long debugging time... 

It is supposed to be used with the ibc-go [TestChain](https://github.com/cosmos/ibc-go/blob/v7.1.0/testing/chain.go#L494). 
With `voteSet := cmttypes.NewVoteSet(chainID, blockHeight, 1, cmtproto.PrecommitType, cmtValSet)` the output is:
```
extEnabled=false:  extensions must be present IFF vote is a non-nil Precommit; present false, vote type 2, is nil false
extEnabled=true:   extensions must be present IFF vote is a non-nil Precommit; present false, vote type 2, is nil false
```
And with `voteSet := cmttypes.NewExtendedVoteSet(chainID, blockHeight, 1, cmtproto.PrecommitType, cmtValSet)`:
```
extEnabled=false: extensions must be present IFF vote is a non-nil Precommit; present false, vote type 2, is nil false
extEnabled=true:  extensions must be present IFF vote is a non-nil Precommit; present false, vote type 2, is nil false
```

As you can see `extSignature` is always empty. It is not set anywhere in the code coming from `MakeExtCommit`.

**Comment by sergio-mena** [comment]
Hi again,
* `MakeExtCommit` (just as `MakeCommit`) is not intended for external use. We know that, technically, the code is currently part of CometBFT production code, but it shouldn't (it should only be accessible to `go test` when unit-testing CometBFT). We will fix that. Please do not use `MakeExtCommit` unless you are unit testing CometBFT's internals, any other usage is not officially supported.
* Now, regarding your particular problem
  * Looking at your log line, I see that  the problem seems to be that you are calling `SignAndCheckVote` at some point, but your implementation of `SignVote`, which is part of `PrivValidator` interface, is not producing the extended signature
  * So your problem is located in the second parameter in your call to `SignAndCheckVote`. You should pass something that properly implements `SignVote` (something like [this](https://github.com/cometbft/cometbft/blob/e633b4553/privval/file.go#L262))

More generally, I would like to better understand why you need to get so deep into consensus implementation logic if what you are testing is the integration of the whole CometBFT. We acknowledge that many of these functions (e.g., `NewVoteSet`, `NewExtendedVoteSet`) are public, but they are so low level that we may refactor them in upcoming releases (they are manly public because we use them in other CometBFT internal packages, but in principle they are not intended to be used externally). We would be willing to have a synchronous conversation if that would help.

**Comment by alpe** [comment]
Thanks again for your help!
Just to address the concerns: I am working on the SDK 50 upgrade for Wasmd. I was just looking for a solution that works with ibc-go as before. No intend to use this for anything else than tests.

The validator impl used for tests was a [mock](https://github.com/cosmos/ibc-go/blob/main/testing/chain.go#L175) in ibc-go. With `_, privVal := cmttypes.RandValidator(false, 100)` I don't run into the same error. Thanks for pointing to the validator sign method! 
I don't need the extended vote, just any solution that would give me a valid Commit object. It would be good if you could consider some helper method as part of your stable api in the future. The IBC-go testing framework is widely used and a core part of the wasmd test strategy. 

i can confirm now that it does not fail with the reported error on extended and non extended voteSet/ flag. 👍
