### ISSUE TITLE
Let RPC report a block's gas_wanted and gas_used

### ISSUE THREAD

**Issue by webmaster128** [cometbft/cometbft#1024]
## Summary

Chains configure a block gas limit via `consensus_params.block.max_gas`. However, I currently see no way to monitor the gas usage using Tendermint RPC.

## Problem Definition

As a user I would like to get an overview of the gas wanted and gas used values over the chain's blocks. This is important to evaluate if `consensus_params.block.max_gas` was set to a sane value and how gas usage and block times correlate. Unfortunately there seems to be no straight forward way to read those values on a per-block basis from Tendermint RPC.

Mintscan also wants to show those values here: https://www.mintscan.io/cosmos/blocks/12471351

If I had to calculate the value client-side now, I had to do the following, right?
1. Get /block_results and look into `results`
2. Sum up `gas_used` and `gas_wanted`

This seems a bit cumbersome as those values should be available at block level anyways (at least when the `max_gas` limit is checked). Also I am unsure if there is gas usage outside of transactions (like begin/end block execution).

## Proposal

Making `gas_used` and `gas_wanted` available in /block or /blockchain RPC endpoints would be much appreciated from a client library dev.

-----------

Of course, if I misunderstood something here, let me know. I'm not horribly familiar with Tendermint details. Thanks!

**Comment by alijnmerchant21** [comment]
Hi @webmaster128 thanks for opening the issue. AFAIK [ADR 101](https://github.com/cometbft/cometbft/blob/thane/adr-084-data-companion-pull-api/docs/architecture/adr-101-data-companion-pull-api.md) partially addresses this issue you have raised. 

Although this feature is in our minds, there are other concerns that need our urgent attention. So we will be de-prioritizing this issue and come back to it later. 

Thanks!

**Comment by andynog** [comment]
I think that you approach of summing it up on client side is OK. On the server side you could return a sum for the block but that would only be offloading this computation from the client to the server and since it's a minimal cost to sum it up not sure if the priority on getting this is very high.

**Comment by webmaster128** [comment]
It's not only a caclulation but additional network requests. See https://github.com/noislabs/pingpong/blob/01e89799e43ae3927c4afffa13c58c8bb64e8d42/blocks.ts#L26-L30.

I think most of my request was motivated by not knowing if all block gas is spent and transactions or can be spent elsewhere. But it seems like tx gas is the only thing that Comet tracks and reports. As long as this is the case, the addition is indeed not very important.

I think overall it would be nice if Comet also tracked gas usage outside of transactions. But I'm not familiar enough with the architecture to know if this is feasible.

**Comment by andynog** [comment]
Hi @webmaster128, I believe that CometBFT uses mostly the `GastWanted` to validate a few things, such as [gas_wanted against max_gas such as in the mempool logic](https://github.com/cometbft/cometbft/blob/8df0aaf4094d5acef66dbbcb0eec530f94159852/mempool/mempool.go#L144). 

The `GasUsed` is usually an application "concern". For example in the SDK you have logic to track the [consumption of gas.](https://github.com/cosmos/cosmos-sdk/blob/5621d9d80736d6025c0f73263947e543fe88793f/store/types/gas.go#L41)

CometBFT has the `GasUsed` values in the [transaction results](https://github.com/cometbft/cometbft/blob/8df0aaf4094d5acef66dbbcb0eec530f94159852/rpc/core/types/responses.go#L56) and that's why it's [returned in the `/block_results`](https://github.com/cometbft/cometbft/blob/8df0aaf4094d5acef66dbbcb0eec530f94159852/rpc/core/blocks.go#L195).

In your logic, seems you're getting the `block_size` from the `/blockchain` information and calculating against the gas? But the `block_size` is the [size of the block in bytes](https://github.com/cometbft/cometbft/blob/8df0aaf4094d5acef66dbbcb0eec530f94159852/types/block.go#L171). 

What you probably want is to do a ratio of `gas_used` against the block `max gas` which you can find per block [in the `/consensus_params` endpoint](https://cosmos-rpc.easy2stake.com/consensus_params?height=15174001). The `max_gas` I'd think would not change that frequently but it might change so it's safer to check it per height, unfortunately it's a extra request

Does it make sense ?

**Comment by webmaster128** [comment]
I see, thank you.

> In your logic, seems you're getting the `block_size` from the `/blockchain` information and calculating against the gas? But the `block_size` is the [size of the block in bytes](https://github.com/cometbft/cometbft/blob/8df0aaf4094d5acef66dbbcb0eec530f94159852/types/block.go#L171).
> 
> What you probably want is to do a ratio of `gas_used` against the block `max gas` which you can find per block [in the `/consensus_params` endpoint](https://cosmos-rpc.easy2stake.com/consensus_params?height=15174001). The `max_gas` I'd think would not change that frequently but it might change so it's safer to check it per height, unfortunately it's an extra request

The app tracks two different things here:
1. Utilization (i.e. how full is the block) in `gas_wanted / max_gas` where max_gas is hardcoded as 10M. Gas used is not so relevant here since unused gas cannot be used by anyone else.
2. The block size in KiB

That being said, feel free to close as wontfix or out of scope. I don't have an urgent need for it and given the explanations it makes probably sense as is.

**Comment by andynog** [comment]
Sure @webmaster128, I will close this for now. Feel free to reach out again for future needs !

**Comment by webmaster128** [comment]
🤝 thanks!
