### ISSUE TITLE
`ProcessProposal`: avoid calls when we know one correct process has already accepted it

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#1230]
In the current implementation of `ProcessProposal` (and spec?), it is called just after doing Comet-level validations on the received proposal block.

However, there are some cases where the local node can conclude that the received proposal has already been processed and accepted by another correct node's `ProcessProposal`.

Since `ProcessProposal`'s main goal is to detect and drop bad proposals from byzantine validators, calling `ProcessProposal` on a proposal that we _know_ has passed `ProcessProposal` elsewhere is, at minimum, suboptimal.

These are the cases where we _know_ `ProcessProposal` has already accepted the proposal at some correct node:

* If the proposal's `POLRound` is -1 and the proposed block matches the one locally locked (part of line 23 of the arXiv algorithm)
* If the proposal's `POLRound` is not -1 and less than the current round, and
  * we have received 2f+1 (worth of voting power) valid prevotes for the proposed block in `POLRound`, and
    * either `POLRound` is greater than or `LockedRound?
    * or the proposed block matches the one locally locked
    * (line 29 of the arXiv algorithm)
* If the proposed block matches our `ValidBlock`

In the arXiv algorithm, this is equivalent to removing $valid(v)$ from line 29, and changing line 23 as follows:
`if` $(lockedRound_p = −1 ∧ valid(v)) ∨ lockedValue_p = v$ `then`.
Also, we assume that $valid(v)$ does not include `ProcessProposal` in lines 36 and 50 (do we really need to call $valid(v)$ at all there?).

This is a similar reasoning to the one followed to minimize calls to `timely` in the Proposer-Based Timestamp (PBTS) [specification](https://github.com/cometbft/cometbft/pull/1206#issuecomment-1666092213).

@hvanz @lasarojc @BrendanChou

**Comment by nenadmilosevic95** [comment]
We can go even further than proposed. The minimal condition would be receiving $f+1$ (worth of voting power) valid prevotes messages from different validators for the proposed block. They can even be from different rounds because, from the perspective of the ABCI, `ProcessProposal` for the same block should always return the same result no matter the round. This is true because due to the determinism requirements, the output of `ProcessProposal` should exclusively depend on a) the state of the app at the beginning of the current height and
b) the data passed in the ABCI call. Consequently, as we do not pass round information in `ProcessProposal` and we talk about the same height, the output needs to be the same. 

Since all proposed cases satisfy the minimal condition presented here, they are safe.

**Comment by hvanz** [comment]
> - If the proposed block matches our `ValidBlock`

In terms of the pseudo-code, the final version of lines 23 and 29 would be:
`23: if` $(lockedRound_p = −1 ∧ valid(v)) ∨ lockedValue_p = v ∨ validValue_p = v$ `then`
and
`29: if` $lockedRound_p ≤ vr ∨ lockedValue_p = v ∨ validValue_p = v$ `then`

Is it correct?

**Comment by lasarojc** [comment]
Seems correct. But to make it explicit the short-circuiting that should take place, maybe we should 23 as

`23: if` validValuep=v ∨ (lockedRoundp=−1∧valid(v)) ∨ lockedValuep=v `then` 

This will avoid the check if lockedRound = -1 but valid is already set to v.

**Comment by sergio-mena** [comment]
> Is it correct?

Thanks, I realise my intitial pseudocode didn't account for $validValue$. I think it's not 100% correct, because $validValue$ should only affect the execution of $valid(9v)$ not what we end up prevoting.

**Comment by lasarojc** [comment]
23: if (lockedRoundp=−1 && (valid(v) || validValuep=v)) &&  lockedValuep=v then

**Comment by lasarojc** [comment]
> We can go even further than proposed. The minimal condition would be receiving f+1 (worth of voting power) valid prevotes messages from different validators for the proposed block. They can even be from different rounds because, from the perspective of the ABCI, `ProcessProposal` for the same block should always return the same result no matter the round. This is true because due to the determinism requirements, the output of `ProcessProposal` should exclusively depend on a) the state of the app at the beginning of the current height and b) the data passed in the ABCI call. Consequently, as we do not pass round information in `ProcessProposal` and we talk about the same height, the output needs to be the same.
> 
> Since all proposed cases satisfy the minimal condition presented here, they are safe.

Thanks for your comment, @nenadmilosevic95 
We agree with you that the condition might be simplified, with implications in lines 23, 29, 36, and 50.
However, since stronger conditions are already required in lines 28, 36, and 49, there would be no gains there, unless these conditions are also weakened, which would require really changing the algorithm and is out of the scope of this PR.

There could be gains in line 23, but that would require more involved changes and would also help only in the uncommon case of needing multiple rounds to decide. Hence we need to further discuss this change as well, possibly in the context of porting PBTS. It is non-blocking for this PR.

Also, I would like to note that even if ProcessProposal is non-deterministic, your proposal would be valid. The reason is validator don't reject invalid proposals, but simply abstain from voting on them. So as long as votes grow across rounds, at some point the value will be considered valid without querying the app, but this should also be further discussed in the context of porting PBTS and closing #1174
