### ISSUE TITLE
Determine "How" and "How Often" is the genesis file accessed?

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#1286]
In this meta issue, we can highlight the main entry points and access patterns for the genesis file. This will ensure that any work to change the current behavior/functionality not breaking (if possible). There are many enhancements (e.g. remove the genesis from memory) that we plan to do and the information in this meta issue will make it easier to perform the work to develop these enhancements by surfacing the context around the genesis file usage in the project.

These are some of the things we need to get more insights into:

  * [x] When it is accessed via RPC, are all fields used or just some? If only a subset is needed, can we provide users 
  with means to return only the requested part?
  * [x] When the node starts, it loads the entire genesis file into memory, is this needed for the entire lifecycle of a node operation ?
  * [x] Is it possible to load the genesis information on demand ? And free it from memory when it's not needed ?

**Comment by alesforz** [comment]
### When it is accessed via RPC, are all fields used or just some?
There are two RPC APIs that deal with the genesis doc:  `genesis` and `genesis_chunked`. Both return the *entire* genesis doc. 

### If only a subset is needed, can we provide users with means to return only the requested part?
See previous answer.

**Comment by alesforz** [comment]
### When the node starts, it loads the entire genesis file into memory, is this needed for the entire lifecycle of a node operation?
We use the genesis doc [object](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/types/genesis.go#L39):
- to extract the `GenesisTime` in the [`Node.OnStart()`](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node.go#L581) method.
- to [create](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node.go#L731) an [`Environment`](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/rpc/core/env.go#L72) object. `Environment` is a convenience `struct` on which we declare methods implementing the RPC APIs; it stores all the information that the RPC APIs need to serve clients' requests.  
- in the [`Node.GenesisDoc()`](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node.go#L984) method, which returns the entire genesis. [This test](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node_test.go#L118) is the only code that uses it.

**Note**: `Environment` stores not only a pointer to a `GenesisDoc` object, but also a slice storing the genesis doc chunks that we return via the `genesis_chunked` RPC API. Because we [create](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node.go#L755) the chunks right after creating the `Environment` object, this means that **we store 2 copies in memory** of the `GenesisDoc`. 1 copy is the original `GenesisDoc`, the 2nd copy is the sum of the multiple chunks we split it into to serve the RPC APIs's requests.

Based on this usage, I don't think we need the genesis file in memory for the entire lifecycle of a node. The only use of the genesis file after the node's initialization is serving RPC requests, which we could do using a cache (so that me purge the file from memory if not referenced after a while).

**Comment by andynog** [comment]
Thanks @alesforz, this is a great investigation.

One more use case for the genesis is on replay blocks during [handshake](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/internal/consensus/replay.go#L206) in consensus, it seems a reference for the genesis is used by the handshaker but it actually only needs an initial height information from genesis

**Comment by alesforz** [comment]
> Thanks @alesforz, this is a great investigation.
> 
> One more use case for the genesis is on replay blocks during [handshake](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/internal/consensus/replay.go#L206) in consensus, it seems a reference for the genesis is used by the handshaker but it actually only needs an initial height information from genesis

Thanks! I updated my answer above. The method calls on `Handshaker` do use several fields of a `GenesisDoc` but, as I wrote above, it doesn't change things because the GC collects it shortly after.

**Comment by alesforz** [comment]
> ### Is it possible to load the genesis information on demand, and free it from memory when it's not needed ?
> We could, for example, store in the `Node` the `GenesisDocProvider` passed at initialization instead of the contents of the genesis file as we do now. As shown above, the major use case of the genesis post-initialization is serving RPC APIs. Any other (infrequent) use of the genesis file can use the `GenesisDocProvider` to fetch it from disk.

One concern with this solution is that the `GenesisDocProvider` not only retrieves the genesis file from disk but also [computes its hash](https://github.com/cometbft/cometbft/blob/30f527a964e3e324920c719acf612f9d0b1f66b4/node/setup.go#L80). Re-hashing the genesis file on every access introduces a performance overhead, which could degrade the responsiveness of the RPC APIs.

An alternative approach is to avoid storing a reference to the genesis in the `Node`. Since the `Node` always retains its full disk path, we can fetch the genesis file when needed, leveraging the [`Config`](https://github.com/cometbft/cometbft/blob/30f527a964e3e324920c719acf612f9d0b1f66b4/node/node.go#L54). However, this approach bypasses any additional operations performed by a custom `GenesisDocProvider` that users may define to process the `GenesisDoc` after it is read from the file.

**Comment by alesforz** [comment]
I'll summarize the possible solutions and continue the discussion in the tracking issue #1037.

**Comment by jmalicevic** [comment]
> ### If only a subset is needed, can we provide users with means to return only the requested part?
> See previous answer.

I think this was referring more to an investigation of , when the genesis file is fetched, do people really need all the fields from the genesis doc or they for example only want a subset of thsoe fields. And if it is a subset, could we return only what they need instead of sending the whole file.

**Comment by andynog** [comment]
I think we can close this @alesforz. We do have enough context here. I like the idea that one day, we can have a way to get only the parts we need from Genesis on an ad-hoc basis without having to load the whole file in memory. I think we do that because we unmarshal the whole file, but we could do it in different ways, maybe a selective parsing (but that would be just reading the field, but this would not validate the file structure). What usually makes the files huge is the state in the genesis file. Another thinking could be breaking that into a separate file, but it would be more complex to implement).

**Comment by alesforz** [comment]
> > ### If only a subset is needed, can we provide users with means to return only the requested part?
> > See previous answer.
> 
> I think this was referring more to an investigation of , when the genesis file is fetched, do people really need all the fields from the genesis doc or they for example only want a subset of thsoe fields. And if it is a subset, could we return only what they need instead of sending the whole file.

Is there a way to figure this out other than asking the community directly?

**Comment by alesforz** [comment]
> I think we can close this @alesforz. We do have enough context here. I like the idea that one day, we can have a way to get only the parts we need from Genesis on an ad-hoc basis without having to load the whole file in memory. I think we do that because we unmarshal the whole file, but we could do it in different ways, maybe a selective parsing (but that would be just reading the field, but this would not validate the file structure). What usually makes the files huge is the state in the genesis file. Another thinking could be breaking the state into a separate file, but it would be more complex to implement and not sure it is feasible).

It's possible to stream-read a JSON file using a `Decoder`, which avoids loading the entire file into memory (see [this example](https://pkg.go.dev/encoding/json#example-Decoder.Decode-Stream) in the encoding/json package docs). However, our genesis file contains a large amount of data, and JSON serialization doesn't guarantee to keep the order of fields in Go structs. Therefore, implementing this approach would be complex.

**Comment by jmalicevic** [comment]
> Is there a way to figure this out other than asking the community directly?

I don't think so and at the moment the gain if probably smaller than the effort. We could store the file in a way that a query can include the exact field a user wants and fetch only that etc.  But streaming and eliminating at least the second copy of it is already a big gain. I just wanted to make you aware of the context in which this was discussed. We  should also make sure that,internally we are not storing it if we don't need the whole file (like in Node, but that gets deleted anyways). So I think it's all good. We can close the issue.
