### ISSUE TITLE
Do not keep the entire genesis file in memory during node operation

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#1290]
### Context
Based on the findings in #1286, it might be possible to remove the logic that keeps the entire genesis file in memory during node operation. Or at least, load the genesis information on demand only when needed and free it up from memory when not needed. We need to ensure this is not a breaking change and that the current logic that needs to validate/use the genesis information doesn't change any behavior or normal operation. This should be a seamless change that would not require any operational changes. If implemented, it would also be beneficial to provide benchmark reports on the a few metrics before and after this change to demonstrate that are advantages such as less memory footprint during node operation.

### Proposal
See discussion below.

### ToDo
- [x] #4234
- [x] #4248
- [x] Benchmark the difference in a `Node` memory usage between before and after the changes.

**Comment by alesforz** [comment]
After discussions in [#1037](https://github.com/cometbft/cometbft/issues/1037), [#1286](https://github.com/cometbft/cometbft/issues/1286), and offline, we've agreed on the following mitigation strategy:
- **Node Type Modification**: The [`Node`](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node.go#L50) type will no longer store a `GenesisDoc`. As explained in [this comment](https://github.com/cometbft/cometbft/issues/1286#issuecomment-2353309745), the `Node` only requires the `GenesisDoc.GenesisTime` field after initialization. Therefore, the `Node` will now store the `GenesisTime` directly, eliminating the need to hold a pointer to the entire genesis document, thus removing one copy of the genesis from memory.
- **Environment Type Changes**: The [`Environment`](https://github.com/cometbft/cometbft/blob/9e25845d45329ad17dddbace0345e8e8514926c5/rpc/core/env.go#L72) type will:
    - Store a [pointer to a `GenesisDoc`](https://github.com/cometbft/cometbft/blob/9e25845d45329ad17dddbace0345e8e8514926c5/rpc/core/env.go#L89) if the genesis file size is below a [threshold](https://github.com/cometbft/cometbft/blob/9e25845d45329ad17dddbace0345e8e8514926c5/rpc/core/env.go#L33), currently set to 16 MB.
    - If the genesis file exceeds this threshold, we will split it into 16 MB chunks and store these chunks in memory in [a slice](https://github.com/cometbft/cometbft/blob/9e25845d45329ad17dddbace0345e8e8514926c5/rpc/core/env.go#L100). In this case, the pointer to the `GenesisDoc` will be `nil`.
- **API Compatibility**: These changes to the `Environment` do *not* break the existing JSON-RPC APIs. Users of `/genesis` and `/genesis_chunked` can continue using them as before. However, if the genesis file is too large (i.e., above the 16 MB threshold), the `/genesis` endpoint will now return an error recommending the use of the `/genesis_streamed` endpoint instead of `/genesis_chunked`.
- **New Endpoint Addition**: We are adding a new `/genesis_streamed` endpoint, which returns the genesis file via streaming over a WebSocket. For more details, see [this comment](https://github.com/cometbft/cometbft/issues/1037#issuecomment-2363726084).

#### Doesn't this solution still require storing one copy of the genesis file in memory? What's the advantage?
Yes, the proposal still requires storing the genesis file in memory. However, it reduces memory usage by storing only **one** copy, whereas we currently store **two** copies (see [this explanation](https://github.com/cometbft/cometbft/issues/1286#issuecomment-2353309745)).

Another advantage is the new `/genesis_streamed` endpoint, which allows clients to download a large genesis file in a single API call, eliminating the need for multiple calls when using the `/genesis_chunked` endpoint.

#### Could we store the genesis chunks on disk instead of in memory?
We could, but before sending the genesis file to a client in response to a request, we need to hash the file to compare it against the genesis hash stored in the database. We must do this *for every request* to ensure the genesis file hasn't been tampered with.
Possible approaches:
- **Store the chunks' offsets into the file instead of the chunks themselves**: This works, but we still need to read and hash the entire genesis file. Although we can hash a file without loading the entire file into memory, we'd have to do it for *every chunk*. Reading and hashing a file of potentially several GBs just to return a small 16MB chunk is a significant overhead.
- **Store the hashes of the chunks in our database**: This also works; we would only need to hash each chunk and compare it against the stored hash. However, for a 1GB genesis file, this means storing 64 hashes in the database, and even more for larger files. We believe this adds too much storage overhead.
- **Store the genesis file on disk and chunk it upon reception of a request**: chunking a file of potentially several GBs for every request introduces too much overhead. 

Therefore, to support the `/genesis_chunked` endpoint, we believe that storing the chunks in memory is the lesser evil.

#### gRPC APIs
We are currently implementing the gRPC APIs, which will support downloading large genesis files only via gRPC streaming. Therefore, we will no longer need to store chunks of the genesis file for these APIs.

(cc @jmalicevic)

**Comment by melekes** [comment]
It's great to see some progress here 👍

**Comment by sergio-mena** [comment]
Hi @alesforz, sorry for some delay taking a look at [this](https://github.com/cometbft/cometbft/issues/1290#issuecomment-2377326927).
Here are my comments:

**Initial section**. Some comments on `/genesis_streamed` serving the whole genesis via a websocket.
I have my doubts that we want this, at least for now:
  * Even in stream format, I think this may risk consuming too many resources in the node. I would only implement this if we have strong feedback from users reporting (valid) problems using the existing two endpoints (i.e., `/genesis` and `/genesis_chunked`)
  * Also, in the mid term, we would like to transition our current JSON-RPC interface to gRPC, we already have some functionality on gRPC (@jmalicevic has more details here). So I'm skeptical about spending some engineering time with important improvements to the RPC interface. It's probably better to invest that time on implementing this in our current (or future) gRPC interfaces.

**Section "tradeoffs"**. I would consider a small LRU cache in memory of chunks recently requested (in case, e.g., users manually request the same chunk several times, or a poorly written script repeats steps). But TBH, this is just an idea, no strong opinion on this... actually, I wouldn't bother unless evidence in the form of performance metrics of similar shows us that we need the LRU cache.

**Section "gRPC APIs"**. This supports my point above of not implementing `/genesis_streamed` in RPC... unless some important users provides a **valid** reason why they can't wait for the gRPC version.
