### ISSUE TITLE
Modifying transactions in PrepareProposal 

### ISSUE THREAD

**Issue by k0marov** [cometbft/cometbft#1563]
### Setup

**v0.38**

**Have you tried the latest version**: yes

**kvstore**

**Environment**:
- **MacOS**

### What happened?

I tried to use PrepareProposal for adding, for example, "test_" prefix for every kvstore key.  
(I know that it can be done in FinalizeBlock, but my actual usecase is different, this is just a minimal setup to reproduce).

What happened is that the transaction I sent through jsonrpc did change, but cometbft got into an infinite loop of replaying this transaction. 

I understand that it's because the transaction's hash changed. But it is stated in the docs that I can use PrepareProposal for modifying transactions. How do I do it then if modifying the transaction changes its hash and thus makes cometbft replay it infinitely? 

### What did you expect to happen?

Every transaction is added a "test_" prefix 

### How to reproduce it

Just use kvstore from the guide and modify PrepareProposal like this: 

```go
func (app *Application) PrepareProposal(_ context.Context, proposal *abcitypes.RequestPrepareProposal) (*abcitypes.ResponsePrepareProposal, error) {
	for i, tx := range proposal.Txs {
		proposal.Txs[i] = append([]byte("test_"), tx...)
	}
	return &abcitypes.ResponsePrepareProposal{Txs: proposal.Txs}, nil
}
```

**Comment by melekes** [comment]
Maybe you forgot to accept this proposal:

```go
func (app *KVStoreApplication) ProcessProposal(_ context.Context, proposal *abcitypes.RequestProcessProposal) (*abcitypes.ResponseProcessProposal, error) {
    return &abcitypes.ResponseProcessProposal{Status: abcitypes.ResponseProcessProposal_ACCEPT}, nil
}
```

?

**Comment by k0marov** [comment]
No, ProcessProposal is just like you quoted.

**Comment by melekes** [comment]
> How do I do it then if modifying the transaction changes its hash and thus makes cometbft replay it infinitely?

After CometBFT commits a block, it replies all transactions from the mempool that it thinks were not committed. And since you're modifying all transactions during `PrepareProposal`, the original transactions are still in the mempool. 

You need to invalidate them to remove them from the mempool. You can do so by checking that you've committed the modified versions:

```go
func (app *KVStoreApplication) CheckTx(_ context.Context, check *abcitypes.RequestCheckTx) (*abcitypes.ResponseCheckTx, error) {
	// If we've already committed modified version of the tx, reject the original
	dbErr := app.db.View(func(txn *badger.Txn) error {
		parts := bytes.SplitN(check.Tx, []byte("="), 2)
		key := parts[0]
		item, err := txn.Get(append([]byte("test_"), key...))
		if err != nil {
			return err
		}

		return item.Value(func(val []byte) error {
			return nil
		})
	})
	if dbErr == nil {
		return &abcitypes.ResponseCheckTx{Code: 1}, nil
	}

	code := app.isValid(check.Tx)
	return &abcitypes.ResponseCheckTx{Code: code}, nil
}
```

One way to speed up things here is to check whenever it's a new OR replied transaction. 

```go
func (app *KVStoreApplication) CheckTx(_ context.Context, check *abcitypes.RequestCheckTx) (*abcitypes.ResponseCheckTx, error) {
        // Remove all transactions from the mempool (NOTE: it's possible that this removes uncommitted transactions)
	if check.Type == abcitypes.CheckTxType_Recheck {
	     return &abcitypes.ResponseCheckTx{Code: 1}, nil
        }

	code := app.isValid(check.Tx)
	return &abcitypes.ResponseCheckTx{Code: code}, nil
}
```

Now, you can't know that all transactions from the mempool were committed because it's possible to run out of max gas or block size. So, this approach comes with a downside. If transaction A was not sent to any other connected peers and this node created a block (without transaction A because the block was full), then transaction A will be removed even though it was not committed. Please keep that in mind.

If you have any other questions, please let us know! Otherwise, I'm going to close this as resolved.
