### ISSUE TITLE
Adding support for OR queries

### ISSUE THREAD

**Issue by ducksquaddd** [cometbft/cometbft#1569]
### Summary
Currently Comet only support the 'AND' keyword, This feature request proposes the addition of the ‘OR’ keyword to enhance the flexibility of transaction searches.

### Problem Definition

Right now, I would need to make multiple requests to filter transactions based on different conditions. For instance, to find transactions where either the transfer.sender is a specific address or the transfer.recipient is a specific address, I need to make two separate requests.

The implementation of the OR operator would make this one single request

### Proposal

Modification in the parser function to implement an OR operator

**Comment by andynog** [comment]
Hello @ducksquaddd, 

Thank you for bringing up this issue. We completely understand your need for an effective way to query using 'OR' clauses. 

However, due to the limitations of the indexer in CometBFT, we have come to a decision that offering APIs for developers to create their own Data Companion solutions would be a better approach. This way, developers can create custom indexers that are tailored to their specific use cases, providing better results. 

You can learn more about the Data Companion solution by visiting https://github.com/cometbft/cometbft/blob/main/docs/architecture/adr-101-data-companion-pull-api.md.

**Comment by andynog** [comment]
Hi @ducksquaddd, please see comment above. We will close this issue for now since we will not work on a solution due to the fact we're focusing on alternative solutions to this problem. 

But if you'd like to contribute with a solution to this problem, please feel free to re-open it and submit a PR and we will be happy to review the code. Thanks!
