### ISSUE TITLE
About `some block time` in config.toml will affect the selection of block producer? 

### ISSUE THREAD

**Issue by VegeBun-csj** [cometbft/cometbft#1586]
Hello, friends from the community. I conducted an experiment on a chain launched with Tendemint and Cosmos SDK and had some questions about the selection of block producers. Here's my experiment(using cosmos-sdk v0.47.3, comebft v0.37.2):

- I launched a chain using Cosmos SDK.
- started two validator nodes with equal stake amounts. 

I observed that both nodes took turns to produce blocks, which aligns with the principles of Tendermint's round-robin consensus.
Now, let's make some configuration changes on top of the default settings mentioned above:
- The first node uses the default consensus configuration with:
<img width="964" alt="image" src="https://github.com/tendermint/tendermint/assets/39252213/9c5e747e-fa36-4fe2-b207-1b4720f658b4">

while the second node modifies the consensus field in the config.yaml with this: 
<img width="1027" alt="image" src="https://github.com/tendermint/tendermint/assets/39252213/3034c95f-3b4b-4631-a0cc-0093d61bc705">

At this point, I noticed that the round-robin consensus rule wasn't implemented, as `the second node continued to produce blocks while the first node didn't get the chance`. 
<img width="1206" alt="image" src="https://github.com/tendermint/tendermint/assets/39252213/5032a745-4152-4efa-af49-ee84391b2ed3">

**Why is this happening? Can block production time be modified by the validator to gain an advantage in block production? Does this deviate from the definition of round-robin consensus?**

Since the first validator didn't produce blocks, I attempted to increase the delegation amount for the first validator, making Validator1's voting power 60% and Validator2's voting power 40%. Surprisingly, Validator1 also started producing blocks.

- **Why is this?** Isn't block production time determined by voting power? Why is it influenced by the node's block production time configuration? 
- If it's the case, how can we address situations where someone arbitrarily adjusts their block production time to gain an advantage, especially since it seems like these configurations are entirely under the control of the nodes themselves?

**Comment by melekes** [comment]
Hey @VegeBun-csj 👋 Thanks for your question. I will attempt to answer it to the best of my ability, but one of the core engineers may correct me (if needed).

> Why is this happening? Can block production time be modified by the validator to gain an advantage in block production? Does this deviate from the definition of round-robin consensus?

It happens because you only have two nodes. Let me explain. 

Imagine if you had a 3rd validator (all with equal stake). Validator #2 lowers `timeout_propose` to 1s. Now when validator #2 proposes three blocks in a row (because the other two validators #1 and #3 have 3s timeouts), only one will be committed because validator #2 will not have a majority of votes (2/3) to justify committing blocks. I.e., the network moves with the speed of 2/3+ nodes. In your setup (two nodes), since validator #2 had a 2/3+ majority, the network moved with 1s block times, leaving almost zero chances for validator #1 to produce blocks. Increasing the validator's #1 voting power increases the frequency of being a proposer in the current round, leaving it a chance to propose at least some blocks.

> Can block production time be modified by the validator to gain an advantage in block production?

If 2/3+ of validators (actually voting power) do this, yes.

> Does this deviate from the definition of round-robin consensus?

In a way (although this depends on the definition used), this guarantees liveness as 2/3+ of the network can always make progress! If you think you've found an error in the specification of the consensus algorithm (link below) or docs, please tell us so.

> Isn't block production time determined by voting power? Why is it influenced by the node's block production time configuration?

To ensure the liveness of the network.

> If this's the case, how can we address situations where someone arbitrarily adjusts their block production time to gain an advantage, especially since it seems like these configurations are entirely under the control of the nodes themselves?

You can ensure your voting power is sufficiently decentralized (more validators are better until a certain point).

I hope that helps!

Additional refs:

* https://docs.cometbft.com/v0.37/core/configuration#consensus-timeouts-explained
* https://arxiv.org/pdf/1807.04938.pdf

**Comment by andynog** [comment]
Hi @VegeBun-csj , please let us know if the answer provided by @melekes helped answers your questions. If you are satisfied please let us know if we can close this issue.

**Comment by melekes** [comment]
Let's not wait here. We can always reopen the issue if any questions arise. I'm going to close this for now.

**Comment by VegeBun-csj** [comment]
@melekes 
>In your setup (two nodes), since validator2 had a 2/3+ majority, the network moved with 1s block times, leaving almost zero chances for validator1 to produce blocks

This is not correct, in my case, validator2 had 1/3 voting power and less timeout,but validator1 had 2/3 majority. The result is validator2 leaving zero chances for validator1 to produce blocks. So in my case, (two validators) timeout maybe affect the chance of block producer more but not the voting power.
Only when the validator1's voting power increased to 2/3 and validator2 had 1/3, validator1 can produce block.

I still confused about the first answer, Can you explain it again? Because i still cannot understand how timeout and voting power both affect the block producer:) thanks very much.

**Comment by melekes** [comment]
> validator1 had 2/3 majority. 

validator #1 needs 2/3+ majority to make progress = 66% in every round where it's a proposer. otherwise, if it has < 66%, it needs a vote from validator #2 to proceed.

**Comment by VegeBun-csj** [comment]
> > validator1 had 2/3 majority.
> 
> validator #1 needs 2/3+ majority to make progress = 66% in every round where it's a proposer. otherwise, if it has < 66%, it needs a vote from validator #2 to proceed.


To some extent, I understand that what you're saying is when there's a timeout to compete for block production rights, it's necessary to offset the impact of the timeout by having a greater voting power to gain the right to produce blocks. So, in practice, in a decentralized network with enough decentralization, this impact caused by timeout can be overridden by voting power, is that correct?

**Comment by melekes** [comment]
> > > validator1 had 2/3 majority.
> > 
> > 
> > validator #1 needs 2/3+ majority to make progress = 66% in every round where it's a proposer. otherwise, if it has < 66%, it needs a vote from validator #2 to proceed.
> 
> To some extent, I understand that what you're saying is when there's a timeout to compete for block production rights, it's necessary to offset the impact of the timeout by having a greater voting power to gain the right to produce blocks. So, in practice, in a decentralized network with enough decentralization, this impact caused by timeout can be overridden by voting power, is that correct?

yes

**Comment by VegeBun-csj** [comment]
@melekes  Thanks melekes. Got it.

**Comment by melekes** [comment]
We should add a paragraph to the docs about this.

**Comment by melekes** [comment]
Attempted explaining ^ in https://github.com/cometbft/cometbft/pull/1798. Please comment on the PR if you think it's not sufficiently clear.

**Comment by VegeBun-csj** [comment]
@melekes good job, i have no other questions. Thanks for your explaination :)
