### ISSUE TITLE
Proposer often gossips the first block parts to all peers

### ISSUE THREAD

**Issue by evan-forbes** [cometbft/cometbft#1742]
ref https://github.com/celestiaorg/celestia-core/issues/1145

Currently when the proposer creates a block, it will send each block part over the internal message queue. This can actually take a some time. The gossip routine doesn't account for that and will start gossiping immediately, which results in sending the same block parts to all peers instead of sending them randomly.

This is why when we trace the block parts, we often see them downloaded in order. This also defeats the purpose of using block parts entirely, as we end up gossiping the entire block to all peers.

below we can see a diagram that illustrates block propagation for a given height that shows this occuring. on the y axis we have block part indexes, and on the x axis

![broken_proposer](https://github.com/celestiaorg/celestia-core/assets/42654277/6453e488-453f-417e-b088-26cd0f909ac0)

If we [simply wait](https://github.com/celestiaorg/celestia-core/commit/b6b57b9109b0880cf67967e60a6d6209f2ce0fb1) for the block to go over the internal message queue before gossiping, it fixes the issue and we gossip all of the block parts randomly!

There's still quite a bit of room to optimize which parts we send to each peer. One simple non-breaking change would be to not gossip block parts entirely randomly. Instead, we should keep track of which parts have been sent to any peer, and prefer to send a part to a peer if it has been sent to fewer peers.

While I'm convinced that this was one of the bottlenecks, it certainly isn't the only one since this change still doesn't increase throughput on its own. ATM, I think there's quite a lot of backup occurring, because we frequently end up receiving block parts super late.

![fixed_proposer](https://github.com/celestiaorg/celestia-core/assets/42654277/75db2b12-fbc2-40d3-b182-75d1d6617342)

**Comment by lasarojc** [comment]
Thanks @evan-forbes for sharing these very interesting results. A few questions

- Which version of the software are you using?
- Do you have the data for a block producer? I would like to see how the block propagates out of the now that from the the beginning already has all blocks
- Would you be able to reproduce this experiment with a branch having the `blockPartMessage` being propagated as well?

**Comment by evan-forbes** [comment]
I'm using [this branch](https://github.com/celestiaorg/celestia-core/tree/evan/big-blonks-2), which is based on v0.34

what is meant by blockPartMessage, do you mean HasProposalBlockPartMessage?

**Comment by melekes** [comment]
> what is meant by blockPartMessage, do you mean HasProposalBlockPartMessage?

Yes

**Comment by evan-forbes** [comment]
yeah, we've ran similar experiments on it a few weeks ago, but not combined with the above fix. I'll try and get one through today. Interestingly neither of the above actually increases throughput, at least in the experiements we're running.

**Comment by melekes** [comment]
> I'll try and get one through today.

@evan-forbes have you been able to conduct the experiment w/ the fix?

**Comment by cason** [comment]
> If we [simply wait](https://github.com/celestiaorg/celestia-core/commit/b6b57b9109b0880cf67967e60a6d6209f2ce0fb1) for the block to go over the internal message queue before gossiping, it fixes the issue and we gossip all of the block parts randomly!

So, you are accessing a private method from `state.go` without acquiring the state lock, this may cause problems.

**Comment by cason** [comment]
> Would you be able to reproduce this experiment with a branch having the blockPartMessage being propagated as well?

This might alleviate the redundancy, but does not address the problem here. Notice that we are talking about the proposer propagating a block for "the first time". Namely, no one has the block yet, so no one will send us the `HasBlockPart` message.

**Comment by cason** [comment]
I can intuitively confirm the reported issue.

The proposer indeed adds the `Proposal` and all `BlockPart` messages to the internal message queue. This queue is consumed by the main consensus routine (`cs.receiveRoutine`). We first accept our own `Proposal`, which configures the block we are looking for (`cs.ProposalBlockParts`), then we process each block part in order.

Processing local messages takes time, longer than processing remote messages, because we synchronously persist internal messages to the WAL (`cs.wal.WriteSync(mi)`). I suspect that this is the main reason for the delay when processing block parts (or between processing different parts).

We need to accept a block part in order to render it available to the consensus gossip layer. Since we have to pay for the cost of persisting each block part before accepting it, the gossip routines will likely find a `Proposal` to send, then the first block part, then only two block parts (thus sending the second), etc. etc.

**Comment by cason** [comment]
> yeah I've ran a version with the combined fix and unfortunatley we are still hitting the same throughput limitations as before. 

More as a suggestion, having in mind my previous comment: have you tried to not use the WAL to persist consensus messages/events? Notice that since the disk is slower than the network, I wouldn't expect a protocol for the crash-recovery model to be network bound. Moreover, we also have the processing cost of producing/verifying signatures. In other words, I don't expect BFT protocols in general to be network bound.

**Comment by adizere** [comment]
We did some investigations into disabling the WAL. Example of the two approaches of disabled WAL: 090bd497c687603a036e5dfac80ccf1d7ec119b2 & e2448b9b4bf6d1d206f7a2574374bc660ce75dfc. 

Experimental setup:
- 10 nodes, all validators
- colocated in the same DO datacenter, so network latency is very low and throughput very high
- transaction size 4kb
- block max size 100mb
- experiment manifest [gist](https://gist.github.com/adizere/bf0337187456d665787ba2bbccea3b27)

What we found is that completely disabling the WAL can have up to ~30% positive impact reducing of block latency. The WAL is on the critical path of building/proposing blocks so this is expected, but we didn't know how much of an impact this might have. We expect that in WAN networks where the latency/bandwidth between nodes dominates bigger part of block lifecycle the impact of disabling WAL will be lower than 30%.

#### Block rate per minute

The two dips on the left side of the white line show the two surges of workload in the experiment with vanilla "With WAL" CometBFT v1.0-alpha.2. The two dips on the right show the workload surges in the setup that has no WAL (commit 090bd497c687603a036e5dfac80ccf1d7ec119b2; e2448b9b4bf6d1d206f7a2574374bc660ce75dfc showed similar but slightly less improvements).

- With WAL the average block rate is around 9 blocks per minute during surges
- Without WAL, it's 12 blocks per minute

<img width="1109" alt="block-rate" src="https://github.com/cometbft/cometbft/assets/1757002/1d8141b2-b6d2-456b-999e-8b90e6379d60">

#### Tx rate per second

<img width="1113" alt="tx-rate" src="https://github.com/cometbft/cometbft/assets/1757002/ba09154f-c92b-4d22-9d55-86c307586244">

#### Block size bytes

<img width="1109" alt="Screenshot 2024-03-21 at 21 33 38" src="https://github.com/cometbft/cometbft/assets/1757002/8aac4b2d-975d-4dd9-95cc-37e73aa8f369">

Block size bytes average:

<img width="1112" alt="Screenshot 2024-03-21 at 21 34 30" src="https://github.com/cometbft/cometbft/assets/1757002/21faa4dd-1364-445d-bfbd-184d5c6be5cc">

#### Total transactions cleared

This is the `cometbft_consensus_total_txs` Prometheus metric.

<img width="1115" alt="total-tx-cleared" src="https://github.com/cometbft/cometbft/assets/1757002/692d3536-b83b-4a23-b23f-bf923c1dbdfe">


Blocks tend to be smaller with no WAL, because more blocks are being produced and Comet can clear the client workload faster. The average rate of client workload is 8MB/sec (4kb each transaction * 2000 tx/sec) but tm-load-test adapts to `broadcast_tx_response`, so the workload rate in reality is never 8MB/sec, but it depends on how fast Comet can clear transactions. In this plot we can see how much better "no WAL" is in terms of total client workload cleared by around ~9K transactions.

#### Consensus rounds

<img width="1115" alt="consensus-rounds" src="https://github.com/cometbft/cometbft/assets/1757002/f722af60-b21e-4ebd-9ef2-16b822668587">

With no WAL, consensus fails more often to reach decision in round `0`.

## Some takeaways

- With WAL, CometBFT produces bigger blocks, at a slower rate. Without WAL, blocks tend to be smaller, at a faster rate, and with lower incidence of going into round > `0`. The total client workload cleared without WAL throughout the experiment run is higher by ~9K transactions.
- We will further investigate WAL, but do not expect optimizations to bring significant block latency improvements in production networks
- The more important problem we want to tackle on the mid-term is making block production resilient to surges in load: Irrespective of client tx load, as long as the proposer is not faulty/asynchronous, block production should finish in round `0`. This is not what happens (see "consensus rounds" plot).

**Comment by cason** [comment]
I've come up with a potentially simple and non-intrusive solution (I'd say workaround) for this scenario here: https://github.com/cometbft/cometbft/pull/4009

Can you test it to see if the results are the expected?

**Comment by cason** [comment]
@evan-forbes, if you don't mind, I'd close this issue given the solution/workaround implemented by https://github.com/cometbft/cometbft/pull/4009.

**Comment by evan-forbes** [comment]
definitely! thanks
