### ISSUE TITLE
consensus: TestByzantinePrevoteEquivocation is flaky

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#1917]
## Bug Report

TestByzantinePrevoteEquivocation is flaky

### Setup

CI

### Config

CI

### What happened?

Sometimes TestByzantinePrevoteEquivocation works.  Sometimes TestByzantinePrevoteEquivocation does not work. 

In flaky test cases we don't know if it is the code or the test, by the way.  This means that ByzantinePrevoteEquivocation could be malfunctioning.

### What did you expect to happen?

I expect tests to work consistently.

### How to reproduce it

Work on Comet

### Logs

Fail Log
* https://github.com/cometbft/cometbft/actions/runs/7379656614/job/20076181734?pr=1907

Looking at the surrounding commits in:

#1907 it is quite clear no relevant changes were made.

Magic Success 1 commit later with no relevant code changes:
* https://github.com/cometbft/cometbft/actions/runs/7379829117/job/20076535412?pr=1907

### Anything else we need to know

While we call these flaky tests, the name doesn't do reality justice.  They're ambiguity as to weather or not one function or another actually works as designed, and they greatly slow development on comet, while making it more expensive.

**Comment by cason** [comment]
After investigating the logs of tests that have failed, I am starting to suspect that in some runs validators _do not receive_ the conflicting votes from height 2. I am sure, from these logs, that validators don't add conflicting votes and don't produce the associated evidence of misbehavior.

I can think on some reasons for the above mentioned behavior:
 - A node receives the conflicting Prevote of height 2 when it already moved to the next height
 - A node does not send one of the conflicting Prevote messages to a peer (we need that, since the Byzantine node splits the network with two conflicting Prevotes) because it realized that that peer does not need it anymore (e.g., it moved to the Precommit round step)
 - A node does not send one of the conflicting Prevote messages to a peer essentially because by randomly picking Prevote messages to send to that peer, it happens it never peak the vote in question before the two cases above are observed.
 
In the failed test case I have found, only one of the 3 correct validators receive both Prevotes. Unfortunately some log messages are not indexed by the node who produces them, but following the second Receive (the one that would be the equivocation), there are messages referring to committing a block. Since the Receive log entry is produced by the reactor, its is always possible that the vote was received (network level), but ignored at consensus level.

**Comment by faddat** [comment]
@cason this sounds to me like the scary place where p2p meets consensus.

**Comment by cason** [comment]
> @cason this sounds to me like the scary place where p2p meets consensus.

Actually, it is the consensus Reactor. This is a kind of problem that we have already spotted in other discussions in terms of producing a more extensive amount of evidences (e.g., amnesia). The point is that we don't keep enough information (from previous heights, mostly) and that we optimize the exchange of consensus messages between peers, which also makes less likely a node to spot an evidence of double voting.

But regarding this test, specifically, I wonder why it covers `Prevote` votes. The really complex are equivocation on `Precommit` votes. They also have the advantage that, once a node moves to the next height, it is still received and processed before the `timeout_commit` expires. Spotting double signing in this case is easier.

**Comment by faddat** [comment]
@cason interesting......

eg: very interesting problem

Don't quite know the solution.

**Comment by cason** [comment]
Also: https://github.com/cometbft/cometbft/issues/1917#issuecomment-1875731440

**Comment by faddat** [comment]
> But regarding this test, specifically, I wonder why it covers Prevote votes. 

Indeed sir

As a validator, I do know that prevotes, on some level, do indeed count for double signs.  It gets a little hand wavy though, and it's worth digging into.  For now, I will try having vals 1 and 2 double sign, and see if that fixes the test

**Comment by adizere** [comment]
Closing as deprioritized.
