### ISSUE TITLE
abci: Precommits added to the `LastCommit` set don't have vote extensions verified

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#2361]
### Setup

**CometBFT version** 

v0.38 and main

### What happened?

Invalid vote extensions are included in the `ExtendedCommitInfo` offered to the ABCI application via `PrepareProposal`.

### What did you expect to happen?

`ExtendedCommitInfo` only includes valid vote extensions.

Moreover, the `LastCommit` field of a block should only contain Precommits whose extensions were accepted by the application.

### How to reproduce it

A validator receives a `Precommit` from the previous height with an invalid vote extension during the `NewHeightRoundStep`.

### How to fix it

There are a few options:

- do not fix
    - instead, inform applications that `PrepareProposal` may receive non-validated extensions
    - the downsides  are
         - 2/3N extensions may be verified twice by the proposer, once in `VerifyVoteExtension` and once in `PrepareProposal`.
         - the `LastCommit` field of a block may contain information of Precommits whose vote extensions are invalid.
- verify the extensions of Precommits received while waiting for `timeout_commit`
    - the downsides are
        -  the application has already moved on to the next height and will now be required to validate extensions from the previous height.
        - makes the spec more complex.
    - a simple and correct option here is to reject extensions for the previous height, however this would impact in the reward distribution (undo what `timeout_commit` is supposed to enable).

**Comment by cason** [comment]
> > * simply rejecting old extensions could impact in reward distribution (undo what `timeout-commit` is supposed to allow.
> 
> Could you clarify this? Are we worried that we won't reward validators that included invalid vote extension? And don't we drop those votes anyway during consensus (i.e. before we enter the commit timeout phase where we wait for extra precommits)?

The simplistic implementation of `VerifyVoteExtension` will be to reject all vote extensions with height previous to the current height. This will make the point of having this additional waiting period useless.

**Comment by ancazamfir** [comment]
Ok, i never thought we would do that. The options says "verify the extensions of Precommits received while ..." and not "reject....". So I wouldn't count it under "Cons" for that option.

**Comment by sergio-mena** [comment]
We had a meeting today to decide how to address this issue (attendees @cason, @lasarojc, @sergio-mena).

First let us describe the options we considered:

  * Option 1a. Clarify the spec: "Some extensions delivered in `PrepareProposal` may not be verified (and explain why), but more than 2/3 will always have been verified". Suggestion for app developers: "use your code for `VerifyVoteExtension` also as part of `PrepareProposal`"
  * Option 1b. Modify ABCI structs (and internal consensus structs) to distinguish unverified votes/extensions from verified votes/extensions when calling `PrepareProposal`.
  * Option 2. When a precommit arrives late (after its the block has already been delivered to the application) we nevertheless call `VerifyVoteExtension` on it. The app will observe a call to `VerifyVoteExtension` for the previous height, but still has the opportunity to verify the extension. In this option, _all_ vote extensions delivered in `PrepareProposal` have been verified by the app
  * Option 3. Refactor the way `timeout_commit` is implemented so that the block is delivered only after `timeout_commit` expires. So all precommits that will be part of LastCommit in the following block could trigger `VerifyVoteExtension` for their extensions having the app always receiving the call for the _present_ height.

These are the decisions we made: 

* First is it obvious Option 3 implies massive changes in the consensus logic, and it is not certain if there will be negative implications performance-wise
* We agree Option 2 is still too risky to backport to `v0.38.x`: it implies a noticeable change in behavior, and many Apps have already implemented against current behavior described in the spec's grammar. Changing it in a point release in `v0.38.x` may lead to unexpected negative consequences for those apps that may have already undergone some testing phases.
* Therefore, we agree we need to go for Option 1.
  * We agree that we believe that Option 1b can be done and backported to v0.38.x without disruption to chains doing point upgrades to `v0.38.x`.
  * But also agreed it's far from trivial to implement
  * Decisions:
    * we will implement Option 1b only when users show the need for this
    * we will go for Option 1a for the time being
* For the long term:
  * not clear whether we would like to implement Option 2, Option 3, or even stay with Option 1
  * so, we agree this should be part of the ABCI 3.0 discussions

Action items
- [x] Update the issue with this text
- [ ] Implement option 1a (fix the spec) -- this should close this issue
- [ ] Contact the teams affected
- [ ] Create a new issuse, explaining options 2 and 3, and hook it to the ABCI 3.0 list in the tracking issue

**Comment by Eric-Warehime** [comment]
In my opinion, changing the spec to match the behavior after the fact (option 3) is also a breaking change just as much as making a change in code (option 2) would be. The reason I say this is that developing a vote extension based oracle around 0.38 did in fact require us to make changes to our proposal handlers in order to compensate for the bug or "change in spec", however you want to refer to it.

The expectation that the application has when using vote extensions is that every VE passed to the prepare proposal handler has passed a VerifyVoteExtension call. In order to compensate for this expectation no longer holding, we have to verify VEs based on state in the previous block. This is also something we need to do in Process Proposal and in general is not an easy thing to do (this might be made easier in the SDK as well as Comet, I'm not sure). 

If the new expectation for applications is to run validation on previous block VEs and by extension previous block state, then it should be easier to reference and access that state in modules. As is, we think we're going to rely on nodes having `EvidenceParams.MaxAgeNumBlocks` set to non-zero in order to access previous state--something which feels brittle overall.

**Comment by lasarojc** [comment]
Thanks for the feedback, @Eric-Warehime 
Given that both the current behavior as well as option 2 require validation using previous state, do you feel that option 3, in spite of delaying block execution, might be a better solution?

**Comment by Eric-Warehime** [comment]
I share your concern over option 3 from a performance perspective. It seems like at worst it could universally increase block times by `timeout_commit` which would probably scare most chains away from ever using vote extensions.

Option 1b seems best from an end user perspective. If I have a quorum of VEs that I know are valid and some additional VEs which have no guarantees of validity, I can choose as an application to use only the pre-validated VEs or attempt to validate the additional VEs after the fact.

That being said, my Comet knowledge isn't great enough to know all the hurdles implementing this in a backwards compatible way entails.
