### ISSUE TITLE
PBTS: define and adapt metrics to debug timely proposals

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#2480]
The main metric to debug PBTS is `ProposalTimestampDifference`. It produces an histogram for the observed difference from the received time for a `Proposal` and the `Proposal` timestamp. Preliminary outputs from QA experiments (#2323) show that this metric is very relevant for debugging and for defining standard values for `SynchronyParams`. 

Two additional metrics were added in context of the previous effort to implement PBTS. They are available on `main` branch: `QuorumPrevoteDelay` and `FullPrevoteDelay`. They should also help the definition of `SynchronyParams`, in particular `MessageDelay`. We have to check, however, how useful are the values returned by them.

We need to check

### Definition of Done

- [x] Investigate the values produced by `QuorumPrevoteDelay` and `FullPrevoteDelay`
- [x] Decide whether to maintain `QuorumPrevoteDelay` and `FullPrevoteDelay` metrics
- [x] Define good representation (buckets) for `ProposalTimestampDifference` metric
- [x] Define whether labeling `ProposalTimestampDifference` with the `is_timely` flag is useful
- [x] Adapt representation (buckets) for `ProposalTimestampDifference` metric if default synchrony paras values are updated after the QA
- [ ] Update PBTS runbook regarding the content and use of the new metrics
- [ ] Update the metrics.md spec, align it to the new comments and semantics

**Comment by cason** [comment]
An experimental setup of metrics, for enabling QA, was defined here: https://github.com/cometbft/cometbft/pull/2479

There is a high level of granularity for `ProposalTimestampDifference`, which might not be ideal for in production networks.

**Comment by cason** [comment]
https://github.com/cometbft/cometbft/issues/2323#issuecomment-1966601461

**Comment by cason** [comment]
Notice that with the current implementation, `ProposalTimestampDifference` is also produced when BFT Time is in use. It is uncertain which value for `id_timely` flag is adopted in this case. Potentially the timely check is performed using the default values for `SynchronyParams`.

**Comment by lasarojc** [comment]
##  Investigate the values produced by QuorumPrevoteDelay and FullPrevoteDelay

These metrics do produce useful information. For example, in the following picture we see that the minimum difference delay was around 135ms, probably reflecting the position of the node on the network.

![image](https://github.com/cometbft/cometbft/assets/2686194/90c08965-4f27-4142-a363-88ffcc607059)

It also shows that the first proposal of many proposers took long to be voted for, but that the situation improved for other proposals.

The amount of data generated by this metric may be too much to maintain, though, as each node keeps tabs on every proposer. If we remove the proposer label, we could still find it out later by correlating spikes in the times with the block times, however with more work. I will recommend that at least for now we keep the metrics but without the proposer label.

Any decision should be revised after the QA is performed with latency simulation enabled.

**Comment by lasarojc** [comment]
## Define good representation (buckets) for ProposalTimestampDifference metric

On a PBTS-based network, with NTP properly working, it is expected that ProposalTimestampDifference metric seldom be negative as NTP's accuracy is of the same order of message delivery delays and therefore negative clock differences are masked as nearly instantaneous delivery of messages.

![image](https://github.com/cometbft/cometbft/assets/2686194/8d68f042-c303-4013-b5fb-130dc3e0cab0)

It is possible that even when NTP is having trouble synchronizing that negative values be masked, since the whole network will probably have trouble delivering.
We therefore need less buckets/detail on negative side.  We do want, however, to be able to differentiate the seldom but expected negative values from abnormally large negative differences. Hence even on the negative side, we need to start with small buckets.

On the positive side we expect larger values due to expected but infrequent message delays due to network topology changes and processing times after delivery, and we need to differentiate small abnormal delays from really large delays that indicate the need for intervention. Hence we use more buckets, with increasing widths. 

We propose here, based on these observations that the following buckets be used. These buckets may be adjusted based on the final QA is performed.
`"-1.5, -1.0, -0.5, -0.2, 0, 0.2, 0.5, 1.0, 1.5, 2.0, 4.0, 8.0"`

**Comment by lasarojc** [comment]
@sergio-mena

**Comment by cason** [comment]
To resolve this issue:

1. Do we keep all the existing metrics?
2. Do we change the computation of them? This is in particular relevant for `ProposalTimestampDifference`: are we distinguishing between `is_timely=true` and `is_timely=false` data?

If we keep everything as it is, we don't need to update the documentation and this issue can be closed.
