### ISSUE TITLE
params: drop `evidence.MaxAgeNumBlocks` in the next major release

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2942]
After PBTS is enabled by default for all chains, we should be able to remove `evidence.MaxAgeNumBlocks` (see https://github.com/tendermint/tendermint/issues/2653#issuecomment-438524834). That's because a timewarp attack (+1/3 cabal modifying block's time) will no longer be possible.

**Comment by andynog** [comment]
My understanding is that [PBTS will not be enabled by default](https://docs.cometbft.com/v1.0/explanation/core/proposer-based-timestamps#enabling-pbts). 

If enable is not enforced then I believe you might still need to keep `evidence.MaxAgeNumBlocks` around, or do a big refactoring of the evidence codebase logic to check if PBTS is enabled or disabled (or when it will be enabled) and then use `MaxAgeNumBlocks` in the logic or not.

But since PBTS can be enabled for a future height via `FeatureParams.PbtsEnableHeight` I guess this just complicates the logic for evidence validation.

**Comment by cason** [comment]
But block times can still be arbitrarily long, due to failures, asynchrony, etc.

So we probably still need to have the requirement of both time interval ("real" time) and blocks committed ("logic" time).

**Comment by melekes** [comment]
> But block times can still be arbitrarily long, due to failures, asynchrony, etc.
> 
> So we probably still need to have the requirement of both time interval ("real" time) and blocks committed ("logic" time).

You mean 1/3+ cabal will still be able to delay block commit for arbitrary time. Therefore we still need `MaxAgeNumBlocks`?
