### ISSUE TITLE
Secret Connection: Remove sync.Pool, and put those buffers in the connection struct

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#3197]
### Summary

In secret connection we use sync.Pool's for some 1024 byte buffers. However these buffers are only ever needed locally within the same thread, so this is a wasted synchronization primitive that does cost us. All reads and writes in secret connection are under a mutex, so we should just make a new buffer in each secret conn struct. 

Impact is ~8% of the current secret connection read time (Get and Put in following pprof): 
![image](https://github.com/cometbft/cometbft/assets/6440154/a885d7a1-976f-4f84-8051-54d10fdcf267)

### Problem Definition

Slight speedup to secret conn

**Comment by cason** [comment]
The problem is that `Read()` and `Write()` are public methods. So while we know that the p2p connection only uses them in a single thread, the implementation is more generic.

Actually, we have other mutexes in those methods that are based on the same assumption. And this is because it implements generic Go interfaces that assume that `Read()` and `Write()` can be called in parallel.

**Comment by ValarDragon** [comment]
Thats not what I mean, the Read method itself already has the mutex! So these buffers would already be mutex protected

**Comment by cason** [comment]
They are protected by different mutexes: 

https://github.com/cometbft/cometbft/blob/67b29879891354ea7c12732d6e9200705eba7c8b/p2p/conn/secret_connection.go#L232-L234

https://github.com/cometbft/cometbft/blob/67b29879891354ea7c12732d6e9200705eba7c8b/p2p/conn/secret_connection.go#L188-L190

We use the `pool` to share buffers between readers and writers...

**Comment by cason** [comment]
What we can have, to reduce contention, are two _unsynchronized_ pools, one for reads, another for writes.

By the way, we import `libp2p` for this buffer pool :D
