### ISSUE TITLE
Max Peer Count Not Respected On Seed Node

### ISSUE THREAD

**Issue by gaia** [cometbft/cometbft#3302]
![image](https://github.com/cometbft/cometbft/assets/87547/17ad619f-ed45-4252-a60e-89c1200a140f)

Osmosis node has been restarted. It IS running as a seed. Does seed mode mean

a) unlimited peers?
b) nodes using it as a seed will show up under peer count?

**Comment by cason** [comment]
This can be the cause: https://github.com/cometbft/cometbft/issues/486

**Comment by cason** [comment]
But if this is a seed node, it is expected to open short-term connection to all addresses it knows in order to retrieve information about other nodes in the network. It also does that to test if peer addresses are valid.

In the same routine, and with the same periodicity, it disconnects to peers from which it is connected by some time:

https://github.com/cometbft/cometbft/blob/67b29879891354ea7c12732d6e9200705eba7c8b/p2p/pex/pex_reactor.go#L741-L751

Where `SeedDisconnectWaitPeriod` is of 28 hours, for some reason I don't know.

**Comment by cason** [comment]
Anyway, the question here is not what is observed in a snapshot, a single point of measurement, but how it evolves over time.

`max_num_inbound_peers` is respected by the seed node. Nodes, however, connect to a seed, ask for address, then disconnect.

`max_num_outbound_peers` is not used by seed nodes.

**Comment by faddat** [comment]
Just a quick question here, I thought that we had gotten rid of the concept of a seed node?

Or is that still a planned future thing?

**Comment by cason** [comment]
@gaia: what is the expected behavior here? That the number of outgoing connections (`max_num_outbound_peers`) is respected by the seed node?

**Comment by gaia** [comment]
> @gaia: what is the expected behavior here? That the number of outgoing connections (`max_num_outbound_peers`) is respected by the seed node?

if a separate seed node app won't be available, yes, that and respecting also `max_num_inbound_peers`.

**Comment by cason** [comment]
> if a separate seed node app won't be available, yes, that and respecting also max_num_inbound_peers.

Any evidence it does not respect this one? It should.
