### ISSUE TITLE
ADR for modular transaction hashing

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#342]
CometBFT should support pluggable cryptographic functionality in order to allow users to address a wider range of use cases than possible with the default cryptography we provide. At present the only way they can do this is to fork the project.

Specific use cases here are to be clarified so the team understands what kinds of interface(s) to implement. Another concern potentially addressed by this is one of mitigating security-related risk through isolation of cryptography-related dependencies (probably our highest-impact dependencies) in order to make them easier to replace in case of vulnerabilities.

The first thing we need here is a design in the form of an ADR, and it must be clear from the ADR as to how the aforementioned use cases could be implemented using the design.

**Comment by itsdevbear** [comment]
+1, we are currently trying to find a cleaner way to implement querying Ethereum formatted transactions on a CometBFT based chain, and the mismatch of RLP vs Sha256 makes it a requirement to store a mapping of EthHashes to CometTxHashes in some sort of off-chain database. We toyed with the idea of storing this in on chain state, but it creates a state bloat issue since these would be non-prunable.

By adding the ability to have pluggable hashes, we could ensure that these transactions would return the identical hash as to what would be created if one was processing the same transaction on Ethereum mainnet.

**Comment by JayT106** [comment]
in the past, we had similar discussions, and ADR
https://github.com/tendermint/tendermint/issues/6539

**Comment by adizere** [comment]
Evmos also signalled the need for this recently. We'll likely prioritize this into v1.

**Comment by adizere** [comment]
Relevant fork PR: https://github.com/evmos/cometbft/pull/1, in particular most important changes seem to be in [types/tx.go](https://github.com/evmos/cometbft/pull/1/files#diff-1861a1e5f502aec1c3bd96661b5024e85d72f1b55c4840977449f1e9f2cd8d00).

**Comment by adizere** [comment]
I had a look over PR https://github.com/evmos/cometbft/pull/1. I tried to understand the impact of porting those changes to CometBFT mainline.

Very much in favor of landing that upstream. Will let @melekes have a more detailed look.

Additionally, I wonder if we can reduce the amount of dependencies app <> CometBFT. Specifically, from a "beginner's mind" perspective it's concerning that CometBFT needs ability to decode transactions. I looked around the codebase and `TxDecoderFn` actually does not seem necessary.

There's 2 cases where CometBFT depends on `TxDecoderFn` in the above PR:

**1/ Mempool.** [Ref here.](https://github.com/cometbft/cometbft/blob/9b437653126053981105579a1c9bbbe179a29811/mempool/reactor.go#L167) I suspect we might be able to remove this dependency. Instead of CometBFT (a) decoding transactions, then (b) passing them decoded to the app for CheckTx; Comet can simply pass to the app in CheckTx raw transactions and the app itself handles decoding while handling CheckTx.

**2/ BlockExecutor.**  [Ref here.](https://github.com/cometbft/cometbft/blob/9b437653126053981105579a1c9bbbe179a29811/state/execution.go#L140-L165) Instead of CometBFT (a) obtaining the `ResponsePrepareProposal`, and then (b) decoding that response; the application can be assumed to provide in `ResponsePrepareProposal` decoded transactions, which Comet subsequently uses to build the block.

We could get to a state where there is no need altogether for `type TxDecoderFn`. Also, `TxI` could look as follows, note only `Hash` seems essential from a quick glance in the codebase:

```go
type TxI interface {
  // Essential
  Hash() []byte

  // The tx comes in as a []byte from wire
  // Bytes() []byte

  // Needed for mempool & mempool cache
  // Replaceable with a basic Digest(), or with
  // the Hash() method above
  // Key() TxKey

  // Needed only for logging, not necessary
  // String() string
}
```

I might be missing something, but the above would likely improve dev UX. Let's clarify if these simplification are feasible and land them.

**Comment by fedekunze** [comment]
```go
  // Needed only for logging, not necessary
  // String() string
```

The `String()` is necessary otherwise the hash is by default represented as uppercases, which is non-compatible with the Ethereum hash format (`0x...`)

**Comment by adizere** [comment]
> // Needed only for logging, not necessary
>   // String() string
> The `String()` is necessary otherwise the hash is by default represented as uppercases, which is non-compatible with the Ethereum hash format (`0x...`)

Good, we'll keep it then.
