### ISSUE TITLE
`DuplicateVoteEvidence` json serialization uses mixed-casing

### ISSUE THREAD

**Issue by benluelo** [cometbft/cometbft#3528]
`DuplicateVoteEvidence` is missing json tags on 3 of it's fields, causing some of the fields to be serialized as PascalCase: https://github.com/cometbft/cometbft/blob/2fa55d440c36e8157261da694c0a65d5d510041a/types/evidence.go#L41-L43

looks like this was addressed previously in tendermint (https://github.com/tendermint/tendermint/pull/4959), but new fields have been added since which do not have the tags https://github.com/tendermint/tendermint/commit/9d354c842ed3b71a6ff4577ccfbb45a699dd9302#diff-cb290f27b7c170773cbdcfce4b7b612bd82bc7cf16a1d74c923f1c53462f49e5R39-R42

**Comment by cason** [comment]
Hey, thank you for reporting. Can you provide the context where this information is serialized? The ABCI-provided evidence is not of this type, but a `Misbehavior`, defined using protobuf.

**Comment by benluelo** [comment]
it's in the json rpc, specifically this block is where we noticed the issue: https://berav2-testnet-rpc.polkachu.com/block?height=1376378

**Comment by benluelo** [comment]
you can use serde aliases: https://serde.rs/field-attrs.html#alias (this is what I have done as well)

**Comment by romac** [comment]
> you can use serde aliases: https://serde.rs/field-attrs.html#alias (this is what I have done as well)

Yes that's what I had in mind for deserialization, but that won't work for serialization. 

As I see it, we have two options:

a) tendermint-rs picks a different serialization scheme depending on the version of Comet running on the node, which is doable but cumbersome
b) tendermint-rs include both fields in snake_case and PascalCase, and Comet will deserialize only the fields in the specific format it expects (to be confirmed) which is simpler but comes at the expense of more bytes on the wire

Do you see another way?

**Comment by sergio-mena** [comment]
Hi @romac and @benluelo , after a discussion with @alesforz, this is what we propose:

1. We believe that the backports to `v0.38.x` and `v0.37.x` have to be backed out, because the change is breaking the (RPC) API.
2. We will introduce the new json format (snake case) for Evidence field starting from `v1.x`

Now, here are the questions we have for you:

* @benluelo, is the snake_case a "nice-to-have"? If not (i.e., something is breaking), please explain what is breaking
* @romac how cumbersome would it be that `v1.x`, ** from the very first release **, contains _only_ the snake format for Evidence JSON tags (and the old PascalCase format totally disappears in `v1.x`)?

**Comment by benluelo** [comment]
the casing doesn't break anything, it's just inconsistent with the rest of the rpc. it can of course be worked around, but consistency/ least surprise is always best (when it's not breaking existing code of course).

it would be good to document the exact format of the fields for both 1.x and pre-1.x. when I was implementing our rpc client I was unable to find any explicit docs about the json formats and had assumed these fields were snake case like the rest of the rpc - I was very surprised to find our relayer had exploded overnight on a `PascalCase` value 😁
