### ISSUE TITLE
crypto/bls12381: change to minimal-signature-size

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#3624]
We must change BLS pubkey and signature types to minimal-signature-size operations because we care more about signature size! We don't send pubkeys over TCP, we send signatures.

https://github.com/cometbft/cometbft/pull/3603#discussion_r1704118134

**Comment by dynst** [comment]
> We must change BLS pubkey and signature types to minimal-signature-size operations because we care more about signature size! We don't send pubkeys over TCP, we send signatures.

This got reverted from 48-byte [`minimal-signature-size`](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-05#section-2.1) back to `minimal-pubkey-size` in #3860 so that Berachain can implement the (EVM execution client compatible) EngineAPI using this type.

But does every other CometBFT chain have to be bound by the technical constraints Berachain is under? Can we reopen this to add a BLS key for chains that don't need 96 byte signatures for compatibility reasons?
