### ISSUE TITLE
types: add and `ABCIPubKeyType` for `sr25519` key

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#3643]
This key type was introduced by https://github.com/tendermint/tendermint/pull/4190, several years ago.

But we don't have an associated key type in the consensus parameters:

https://github.com/cometbft/cometbft/blob/06669cc51a2b54edbd5f21c24a4504894b67a217/types/params.go#L28-L30

As as result, when fixing https://github.com/cometbft/cometbft/issues/3514 we start having problems on nightly e2e tests because this key type can be used but it is not registered. It can be used because it is declared here:

https://github.com/cometbft/cometbft/blob/06669cc51a2b54edbd5f21c24a4504894b67a217/test/e2e/generator/generate.go#L75

**Comment by andynog** [comment]
I don't think it's #3514 that is causing the nightly tests to fail and the root cause might be something else. Doing some additional troubleshooting, will post more here once I have more context.

**Comment by andynog** [comment]
So, this issue fixes an error `params.Validator.PubKeyTypes[0], sr25519, is an unknown pubkey type` that is happening on e2e nightly due to the changes introduced actually in https://github.com/cometbft/cometbft/pull/3513

So #3644 is good to fix the error above.

But there's another error being triggered after this one is fixed related to `sr25519` and remote signing. 
```
error with private validator socket client: can't get pubkey: encoding: unsupported key sr25519
```

I will open an issue for this other error.
