### ISSUE TITLE
test(e2e): e2e-nightly-test - `TestApp_Tx` failure

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#4108]
# Summary

The e2e-nightly-test has [been failing](https://github.com/cometbft/cometbft/actions/runs/10822968482/job/30027692522) mostly on `v1.x`, but eventually we also get a failure on `main` or another older release.

The failure (see below) can be reproduced in local tests on a Ubuntu VM or on a Mac.

# What happens?

This particular error that has been happening on the e2e-nightly-test quite frequently in the recent past. This usually happens for more than [one particular test](https://github.com/cometbft/cometbft/actions/runs/10822968482/job/30027692522). 

```
         --- FAIL: TestApp_Tx (126.10s)
    --- FAIL: TestApp_Tx/validator04 (120.02s)
        e2e_test.go:64: 
            	Error Trace:	/cometbft/cometbft/test/e2e/tests/app_test.go:98
            	            				/cometbft/cometbft/test/e2e/tests/e2e_test.go:64
            	Error:      	Condition never satisfied
            	Test:       	TestApp_Tx/validator04
            	Messages:   	submitted tx (3227101E53F267854F48B6F58617DF805AC60759934C3412B0C682B9EFB1F5F5) wasn't committed after 30s
FAIL
FAIL	github.com/cometbft/cometbft/test/e2e/tests	153.834s
FAIL
```

This particular test submits a tx to the node and tests if the tx is committed within a timeframe or in a range of blocks (height), if not the test will fail (as shown above). 

The test has a [waitTime](https://github.com/cometbft/cometbft/blob/276996ad958475b69727be2c57d4d0d818849a55/test/e2e/tests/app_test.go#L97) variable that currently is set to `30 seconds` and the application has a [txTTL](https://github.com/cometbft/cometbft/blob/276996ad958475b69727be2c57d4d0d818849a55/test/e2e/app/app.go#L43) (time-to-live) of `5 heights`.

# Problem resolution

Here's some details on how we are trying to solve and troubleshoot the problem.

This will be a tracking issue since these failures might have different root causes:

- [x] #4118
- [x] #4119

# Definition of Done (DoD)

Tests are passing on all branches and the error above is not happening for a period of time (a few days)

**Comment by andynog** [comment]
It seems this [PR](https://github.com/cometbft/cometbft/pull/4109) helps fix the issue.

Ran a `e2e` manual on `v1.x` and finally all tests [passed](https://github.com/cometbft/cometbft/actions/runs/10892334696). Will wait until the scheduled nightly passes a couple of days without failures and if it's all good will close this PR.

**Comment by cason** [comment]
Still failing in the latest nightly run: [here](https://github.com/cometbft/cometbft/actions/runs/10895312130/job/30233342180#step:8:610) and [here](https://github.com/cometbft/cometbft/actions/runs/10895312130/job/30233342791#step:8:653).

But now they are failing in full nodes, which are not validators.

**Comment by andynog** [comment]
Investigation continues.

**Comment by cason** [comment]
So, some additional information gathered from the failures.

First, I was able to reproduce this error in a very simple scenario considering the version of `v1.x` from which @andynog has created a branch with improved logging and other features. It was enough to use the proper manifest, run `start` then `test` and the error was observed.

The core reason for the error was that the node, in the case a validator, did not broadcast the transaction it has received from the RPC endpoint. This transaction was in the mempool however, this was clear when running the re-checktx code, that always found this transaction and eventually evicted in from the mempool.

By the way, among the debugging improvements that are included in this branch, logging at info level whenever the application evicts a transaction to mempool should be part of the main code, as this helps a lot debugging this kind of failure.

Why the transaction was not sent to any peer by the mempool?

No idea. The behavior is non-deterministic, some times the test fails, some times it does not. I have discarded the component that a node did not sent a transaction because of the state of the peer (e.g., it was lagging), but I could not discard the component that transaction was not sent because it was registered in the mempool that the transaction was already sent or received to or from that peer.

In any case, apparently there was a corner case in the complex mempool concurrency model in which a transaction was added to the mempool but forever ignored by the sender routine. Smells like concurrency to me.

----

When considering the current version of `v1.x`, including in particular https://github.com/cometbft/cometbft/pull/4109, it was much harder to reproduce the same issue. Although, as above mentioned, it was observed in the last night execution.

The manifests where the failures have happen are, however, much more complex (more nodes, more perturbations, etc.) and the errors where only observed in full nodes, i.e., non-validators.

Since it is hard to reproduce those failures, we don't know whether the reasons is the same, namely the mempool never broadcasting a transaction received via RPC, or a different one.

**Comment by andynog** [comment]
Just another update. I've ran another `e2e-manual` test on `v1.x` and it all [passed](https://github.com/cometbft/cometbft/actions/runs/10906082393). I believe the last night failures might be related to the CI infrastructure. I haven't been able to reproduce these latest failures yet on my local testing.

**Comment by andynog** [comment]
> So, some additional information gathered from the failures.
> 
> First, I was able to reproduce this error in a very simple scenario considering the version of `v1.x` from which @andynog has created a branch with improved logging and other features. It was enough to use the proper manifest, run `start` then `test` and the error was observed.
> 
> The core reason for the error was that the node, in the case a validator, did not broadcast the transaction it has received from the RPC endpoint. This transaction was in the mempool however, this was clear when running the re-checktx code, that always found this transaction and eventually evicted in from the mempool.
> 
> By the way, among the debugging improvements that are included in this branch, logging at info level whenever the application evicts a transaction to mempool should be part of the main code, as this helps a lot debugging this kind of failure.
> 
> Why the transaction was not sent to any peer by the mempool?
> 
> No idea. The behavior is non-deterministic, some times the test fails, some times it does not. I have discarded the component that a node did not sent a transaction because of the state of the peer (e.g., it was lagging), but I could not discard the component that transaction was not sent because it was registered in the mempool that the transaction was already sent or received to or from that peer.
> 
> In any case, apparently there was a corner case in the complex mempool concurrency model in which a transaction was added to the mempool but forever ignored by the sender routine. Smells like concurrency to me.
> 
> When considering the current version of `v1.x`, including in particular #4109, it was much harder to reproduce the same issue. Although, as above mentioned, it was observed in the last night execution.
> 
> The manifests where the failures have happen are, however, much more complex (more nodes, more perturbations, etc.) and the errors where only observed in full nodes, i.e., non-validators.
> 
> Since it is hard to reproduce those failures, we don't know whether the reasons is the same, namely the mempool never broadcasting a transaction received via RPC, or a different one.

Yes, we should add these additional debug messages to `main` but we need to be careful not to affect [performance](https://github.com/cometbft/cometbft/issues/2847) and do it the right way. I have some ideas to improve the logic related to this issue, there's a PR opened but I might do it in a different way (allow a binary compilation without the debug messages).

**Comment by andynog** [comment]
We had several successful runs on [v1.x](https://github.com/cometbft/cometbft/actions/workflows/e2e-nightly-1x.yml) and no failures on [main](https://github.com/cometbft/cometbft/actions/workflows/e2e-nightly-main.yml) and the problem above is not happening after the two issues have been addressed. 

If the runs over the weekend are successful  I'll close this issue next week.

**Comment by andynog** [comment]
Tests have been passing successfully on v1.x and main, so closing this issue
https://github.com/cometbft/cometbft/actions/workflows/e2e-nightly-1x.yml
https://github.com/cometbft/cometbft/actions/workflows/e2e-nightly-main.yml
