### ISSUE TITLE
p2p/conn: secret connection could be broken, because of not hashing the shared secret

### ISSUE THREAD

**Issue by kristovatlas** [cometbft/cometbft#4350]
Have you addressed this finding in the STS implementation?

https://cyber.orijtech.com/scsec/tendermint-p2p-v1

**Comment by cason** [comment]
The code for establishing a secret connection is essentially the same as in 2021: https://github.com/cometbft/cometbft/blame/v1.x/p2p/conn/secret_connection.go.

**Comment by cason** [comment]
Changing the implementation of the p2p authentication would be a complex breaking change.

When we were informed about this report, we have decided to not apply the suggested changes, for being very disruptive (nodes running the new code would not be able to connect to nodes running the existing code), and also because the second opinions we got back them were not in line with the conclusions of this report.

**Comment by cason** [comment]
Also, I am afraid that this has been thoroughly discussed and the maintainers decided to keep it as-it-is: https://github.com/tendermint/tendermint/issues/3010

**Comment by cason** [comment]
Btw, since we are using the new X25519 function from the standard libraries, an error is returned for low order points.

**Comment by cason** [comment]
I changed the issue title, please avoid using such allegorical and fishing titles, thank you.

**Comment by melekes** [comment]
After careful consideration, we have concluded that **it's not a security issue** for CometBFT because we 

1) use the X25519 function, 
2) use a Merlin transcript for the signed challenge, 
3) use HKDF for the `chacha20poly1305` keys. 

Thus, we are hashing `dhSecret` into HKDF for the keys and into Merlin for the challenge.

If you think we're wrong or have something to add, please drop a comment. Thanks 🙏

**Comment by kristovatlas** [comment]
Thanks for the follow-up.

Sorry about the title, I simply copy/pasted it from the audit report.
