### ISSUE TITLE
Unclear private validator accept connection logic

### ISSUE THREAD

**Issue by corverroos** [cometbft/cometbft#452]
## Bug Report

version: 0.34.27

While diving into the `privval` package source code as part of an investigation into [horcrux](https://github.com/strangelove-ventures/horcrux) we discovered that the "accept connection logic" is unclear.

See [source](https://github.com/cometbft/cometbft/blob/main/privval/signer_listener_endpoint.go#L197-L200). Writing to the unbuffered channel `sl.connectRequestCh` after attempting to accept a connection in `SignerListenerEndpoint.serviceLoop` has no affect. This is because a single goroutine cannot read and write to the same unbuffered channel, it can only do that with buffered channels.

It would therefore be clearer to remove that select statement since it never actually writes to the channel.

If the reasoning behind the serviceLoop is to successfully accept one connection for each `connectRequest` then one could change `connectRequestCh` into a buffered channel with length 1 and only write to it when `acceptNewConnection` errored.

**Comment by corverroos** [comment]
I raised this with Tendermint but they routed me here: https://github.com/tendermint/tendermint/issues/10009

I also created a PR in my local fork that I can move here is it looks good: https://github.com/corverroos/tendermint/pull/1

**Comment by adizere** [comment]
Nice find, thanks for reporting!

We'll need a bit of time to get a deep understanding of this issue since our team is working full capacity to deliver v0.38 this month. Thanks for the patience.

In the meantime, do I understand correctly that this issue does not translate into an incorrect behavior/defect (such as inability to accept conns), but it's more about code hygiene? If it's a defect, that will encourage us to prioritize it. Also, noticed you [added unit tests here](https://github.com/corverroos/tendermint/pull/1/files#diff-4ee06072ffc2a7b65eb156645ff660c4b7826f687e6d221b917599802ddedb29), but not sure I understand the logic; maybe there is also a recipe to reproduce the defect using a couple of nodes in practice?

**Comment by corverroos** [comment]
Hi @adizere, at first I only thought it was a "code hygiene" issue. But then I realised that it is indeed a logic bug.

Basically, the `serviceloop` will not retry `sl.acceptNewConnection()` if it errors. It will only attempt `acceptNewConnection` once and if it errors, it will ignore the error and block waiting to another thread to call `triggerConnect`.

My understanding is that this can cause a "deadlock" with the node not accepting new connections anymore. 

The problem with testing this "using couple of nodes in practice" is that you need `net.Listener.Accept()` to error to trigger this bug. In practice `net.Listener.Accept()` doesn't error. That is why I used a mock listener in the unit test that returns a few initial errors before successfully returning (`err==nil`).

**Comment by adizere** [comment]
Was suspecting that, thanks for clarifying! Too bad there's no reliable way to reproduce the bug. That would have given us a lot more confidence in the proposed changes. Give us some time to parse this, and we'll ping you re: potentially porting https://github.com/corverroos/tendermint/pull/1 here.
