### ISSUE TITLE
mempool/dog: Test performance in networks with diverse maximum number of peers

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4614]
The size of a routing table in the DOG protocol is directly related to the number of peers a node has. We need to evaluate the performance of the protocol when nodes have different number of peers than the default values (`p2p.max_num_inbound_peers = 40` and `p2p.max_num_outbound_peers = 10`)

**Comment by jmalicevic** [comment]
## Varying `redundancy adjustment delta` while also varying the number of peers

The main motivation of this experiment was to understand whether we need to increase or decrease the redundancy interval delta depending on the number of peers. 

During this experiment the load of transactions sent to the nodes was lower than the saturation point to make sure that the pressure on the system comes from the number of potential routes rather then the load itself. 

We also ran an instance of CometBFT without DOG enabled with varying number of peers to 

### Experiment setting

Transaction load: 200tx/s

p2p.max_num_inbound_peers: 5 10 20 60
p2p.max_num_outbound_peers: 10

Mempool.dog_target_redundancy: 1
Mempool.dog_redundancy_adjustment_interval: 1000ms
mempool.dog_redundancy_adjustment_delta: 5% 10% 20%

<img width="1247" alt="peers_sent_gb_peers" src="https://github.com/user-attachments/assets/839b405a-168c-44e6-8690-96fa4203c298">


Regardless of the  number of peers, DOG is able to lower the number of transactions sent but 15minutes was not enough to stabilize the number of transactions when the number of peers of 60. 

This can be observed by looking at the number of duplicate messages received:

<img width="1242" alt="duplicates_peers" src="https://github.com/user-attachments/assets/0814e2ed-8139-4497-858e-74dfd2c99905">


When the number of peers is 60, the number of duplicates does not drop to the same extent as when the number of peers is 40. 

We have therefore performed another run, that lasted longer (30minutes) to verify whether the system will eventually stabilize: 

<img width="1240" alt="30mins_num_peers" src="https://github.com/user-attachments/assets/db6602e9-d154-416b-b1eb-342f4c1fb45e">


In this particular experiment we do not report the number of transactions processed or blocks per minute because the load was low and in all situations  CometBFT was able to maintain a similar throughput, processing the load of 200tx/s.
