### ISSUE TITLE
JSON RPC client: Report that a response returned a bad error code

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#636]
### Setup

**CometBFT version** ~all

**Have you tried the latest version**: yes

### What happened?

When running a ABCI query, through the standard tendermint http client from: github.com/tendermint/tendermint/rpc/client/http , I will occasionally get errors of the form:
```
error unmarshalling: invalid character '<' looking for beginning of value
```

### What did you expect to happen?

By adding a println in the JSON http client, called within this (https://github.com/cometbft/cometbft/blob/main/rpc/jsonrpc/client/http_json_client.go#L213-L216) , I found out that this is due to the HTTP response being:

```
429 Too Many Requests
```

I would have expected to get an error reflecting the actual issue, rather than this incorrect JSON parsing.

Furthermore, I've seen this error in several other contexts. (E.g. mistakenly using http://  instead of https://)

Fixing this will likely be of significant debugging aid to everyone in cosmos.

**Comment by andynog** [comment]
Thanks for reporting this @ValarDragon. We will do some further investigation and work on a fix. Looks like this is an issue with the built-in http client handling the http responses error messages. 

I'd imagine that other clients if they handle the responses properly this should not be an issue (since it seems it's not a server side issue)
