### ISSUE TITLE
abci_query path parameter interpretation does not match documentation

### ISSUE THREAD

**Issue by gibson042** [cometbft/cometbft#666]
(*cloning https://github.com/tendermint/tendermint/issues/10020*)

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): Tendermint 0.34.23

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://main.rpc.agoric.net/

### What happened?
A `GET /abci_query` request with path query parameter as documented at https://docs.cometbft.com/v0.37/rpc/#/ABCI/abci_query (i.e., starting with "/") is rejected:
```sh
$ curl -sS 'https://main.rpc.agoric.net/abci_query?path=/custom/vstorage/data/activityhash'
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32602,
    "message": "Invalid params",
    "data": "error converting http params to arguments: invalid character '/' looking for beginning of value"
  }
}
```

Wrapping that path in double quote characters (as at https://github.com/cometbft/cometbft/blob/main/spec/rpc/README.md#abciquery but without the unexpected `=IHAVENOIDEA`) works:
```sh
$ curl -sS 'https://main.rpc.agoric.net/abci_query?path="/custom/vstorage/data/activityhash"'
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "response": {
      "code": 0,
      "log": "",
      "info": "",
      "index": "0",
      "key": null,
      "value": "ewogICJ2YWx1ZSI6ICIyYTk5YmU3NTIwNTk0MTg5MjlkODExYTA0ZGVlYTE4YjM3NGI3M2IxNTA3Y2ZkMjY2NTYwYzVlYWIwMWViOTk4Igp9",
      "proofOps": null,
      "height": "9225800",
      "codespace": ""
    }
  }
}
```

So does submitting the entire request as POSTed JSON-RPC:
```sh
$ curl -sS https://main.rpc.agoric.net --request POST --header 'Content-Type: application/json' --data \
  '{ "jsonrpc": "2.0", "id": -1, "method": "abci_query", "params": { "path": "/custom/vstorage/data/activityhash" } }'
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "response": {
      "code": 0,
      "log": "",
      "info": "",
      "index": "0",
      "key": null,
      "value": "ewogICJ2YWx1ZSI6ICI2MDMzMDJmZmFlNTVjYmFmYjFiZWE2ZTZmM2E4Y2IxZWU0NGI3ZDBkZGFlYjUzZmE5OTkxMDFiMzcxMzJlOGY3Igp9",
      "proofOps": null,
      "height": "9225809",
      "codespace": ""
    }
  }
}
```

### What did you expect to happen?
I expected the unquoted `path` URL query parameter value to be accepted as documented at https://docs.tendermint.com/v0.34/rpc/#/ABCI/abci_query , rather than rejected for not being JSON.

### How to reproduce it

See above.

### Logs

n/a

### `dump_consensus_state` output

n/a

### Anything else we need to know

The culprit is likely [`httpParamsToArgs`](https://github.com/cometbft/cometbft/blob/607ad0ee37a29aee42d2f1c92717937928db6b52/rpc/jsonrpc/server/http_uri_handler.go#L82-L116), which has not changed since https://github.com/tendermint/tendermint/pull/4968 was merged in 2020.

**Comment by adizere** [comment]
Thanks Richard @gibson042 for filing this, great catch! Seems also relatively easy to fix, though it needs a bit more investigation to find the root cause (likely in a method called from the one you mentioned [httpParamsToArgs](https://github.com/cometbft/cometbft/blob/607ad0ee37a29aee42d2f1c92717937928db6b52/rpc/jsonrpc/server/http_uri_handler.go#L82-L116)).

**Comment by stevenferrer** [comment]
Hi @adizere and @gibson042, 

As per my investigation, the handling of `path` argument is handled by this [line](https://github.com/cometbft/cometbft/blob/v0.37.1/rpc/jsonrpc/server/http_uri_handler.go#L109) where [jsonStringToArg](https://github.com/cometbft/cometbft/blob/v0.37.1/rpc/jsonrpc/server/http_uri_handler.go#L118) tries to parse the `path` value as a JSON. 

As I understand, the `path` should be handled by `nonJSONStringToArg` in this [line](https://github.com/cometbft/cometbft/blob/v0.37.1/rpc/jsonrpc/server/http_uri_handler.go#L142) since it's an unquoted string.  I submitted a PR https://github.com/cometbft/cometbft/pull/864 to try and fix it, please lemme know your thoughts, thanks!

**Comment by stevenferrer** [comment]
It seems one [test](https://github.com/cometbft/cometbft/blob/v0.37.1/rpc/jsonrpc/server/parse_test.go#L173) because it expects that [unquoted strings should error](https://github.com/cometbft/cometbft/blob/v0.37.1/rpc/jsonrpc/server/parse_test.go#L190). Just wondering if this assumption still holds true? If not, then maybe we can safely update the test to not expect an error. Please feel free to share your thoughts, thank you!

**Comment by sergio-mena** [comment]
Taking a look at the backlog for this

**Comment by gibson042** [comment]
Looking at https://github.com/cometbft/cometbft/blob/f695d99dd298469b4c3b285c32a52b2d62370947/docs/core/using-cometbft.md , this appears to be intentional (at least for transactions). If so, the issue could be resolved by updating documentation to clarify—the URLs would be unfortunately ugly, but at least the interface would be clear.

**Comment by sergio-mena** [comment]
## Analysis

I took a look at the way different types are handled or over our RPC. This is what I found out:
* In `v0.34.x`, _string-like_ parameters can be (internally) defined as two types: `string` and `[]byte`
* These are the types taken by (exhaustive list of our RPC endpoints taking _string-like_ params)
  * `abci_query`: `path` is `string`, `data` is `[]byte`
  * `broadcast_tx_*`: `tx` is `[]byte`
  * `block_by_hash`: `hash` is `[]byte`
  * `check_tx`: `tx` is `[]byte`
  * `tx`: `hash` is `[]byte`
  * `tx_search`: `query` is `string`, `order_by` is `string`
  * `block_search`: `query` is `string`, `order_by` is `string`
  
So, as you can see, parameters `query` and `order_by` in endpoints `tx_search` and `block_search` are the only endpoints comparable to parameter `path` in `abci_query` (in that they are internally typed `string`).

## Testing

This is how these three commands behave when double quotes are not used (they all fail). The behavior is consistent.

```
localhost % curl -s 'http://localhost:5701/abci_query?path=/a/path' | jq

{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32602,
    "message": "Invalid params",
    "data": "error converting http params to arguments: invalid character '/' looking for beginning of value"
  }
}
localhost % curl -s 'http://localhost:5701/block_search?query=block.height>10000' | jq
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32602,
    "message": "Invalid params",
    "data": "error converting http params to arguments: invalid character 'b' looking for beginning of value"
  }
}
localhost % curl -s 'http://localhost:5701/tx_search?query=tx.height>10000' | jq
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32602,
    "message": "Invalid params",
    "data": "error converting http params to arguments: invalid character 'x' in literal true (expecting 'r')"
  }
}
```

And this is how the commands behave when double quotes _are_ used. The behavior is also consistent.

```
localhost % curl -s 'http://localhost:5701/abci_query?path="/a/path"' | jq
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "response": {
      "code": 0,
      "log": "",
      "info": "",
      "index": "0",
      "key": null,
      "value": "",
      "proofOps": null,
      "height": "636",
      "codespace": ""
    }
  }
}
localhost % curl -s 'http://localhost:5701/block_search?query="block.height>10000"' | jq
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "blocks": [],
    "total_count": "0"
  }
}
localhost % curl -s 'http://localhost:5701/tx_search?query="tx.height>10000"' | jq
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "txs": [],
    "total_count": "0"
  }
}
localhost %
```

## Conclusion

The behavior reported in this issue is the expected one. We can therefore confirm this is an documentation issue.

**Comment by stevenferrer** [comment]
Hi @sergio-mena, thanks for the analysis. I submitted PR #1015 to update the rpc/openapi spec to add double quotes to `path` param. Please let me know if there are other places that needs to be updated, thanks!

**Comment by sergio-mena** [comment]
Thanks a lot @stevenferrer, for filing #1015. We will take it from there. We will check all over ours docs, to make sure any example for one of those endpoints contains the double quotes

**Comment by alijnmerchant21** [comment]
Thanks - @stevenferrer for filing PR #1015. I have made some changes, reflected in the [commit](https://github.com/cometbft/cometbft/pull/1015/commits/03c039205df87445c58d039b920f3f36f0345197).
Also made a PR #1020 to reflect changes on `0.34`
