### ISSUE TITLE
seed mode: memory leak on p2p/conn.newChannel

### ISSUE THREAD

**Issue by p4u** [cometbft/cometbft#839]
We have detected what looks like a memory leak, it **only happens if the node is configured as seed**. We are using cometbft `v0.37.1`

![image](https://github.com/cometbft/cometbft/assets/1075446/c6f6e1b5-a6ae-4fff-af96-219b6a7c6dcd)

The memory allocation shows that p2p/conn.newChannel is leaking memory.

```
Type: alloc_space
Time: May 16, 2023 at 11:18am (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 8842.26MB, 75.51% of 11709.77MB total
Dropped 932 nodes (cum <= 58.55MB)
Showing top 10 nodes out of 133
      flat  flat%   sum%        cum   cum%
 2982.43MB 25.47% 25.47%  2982.43MB 25.47%  github.com/cometbft/cometbft/p2p/conn.newChannel
 1886.29MB 16.11% 41.58%  1886.29MB 16.11%  github.com/cometbft/cometbft/consensus.(*PeerState).GetRoundState
 1482.77MB 12.66% 54.24%  1482.77MB 12.66%  github.com/cometbft/cometbft/consensus.(*State).GetRoundState
  498.01MB  4.25% 58.49%   617.34MB  5.27%  compress/flate.NewWriter
  487.21MB  4.16% 62.65%   487.21MB  4.16%  regexp/syntax.(*compiler).inst
  426.10MB  3.64% 66.29%   426.10MB  3.64%  bufio.NewWriterSize
  396.54MB  3.39% 69.68%   396.54MB  3.39%  regexp/syntax.(*parser).newRegexp
  352.79MB  3.01% 72.69%   352.79MB  3.01%  regexp.onePassCopy
  175.01MB  1.49% 74.19%   212.52MB  1.81%  regexp/syntax.(*Regexp).Simplify
  155.10MB  1.32% 75.51%   494.32MB  4.22%  github.com/prometheus/client_golang/prometheus.(*Registry).Gather
```

![image](https://github.com/cometbft/cometbft/assets/1075446/333d4348-76d7-45df-9f5e-bae2be425cc9)

The heap also shows the leak on `newChannel`:
```
Build ID: 7f106a1a431c206ad5dae15de2dfce60ff9f7707
Type: inuse_space
Time: May 16, 2023 at 11:22am (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 3384.10MB, 98.19% of 3446.55MB total
Dropped 206 nodes (cum <= 17.23MB)
Showing top 10 nodes out of 27
      flat  flat%   sum%        cum   cum%
 2935.97MB 85.19% 85.19%  2935.97MB 85.19%  github.com/cometbft/cometbft/p2p/conn.newChannel (inline)
  412.22MB 11.96% 97.15%   412.22MB 11.96%  bufio.NewWriterSize (inline)
   29.40MB  0.85% 98.00%    29.40MB  0.85%  os.ReadFile
       6MB  0.17% 98.17%  3362.20MB 97.55%  github.com/cometbft/cometbft/p2p/conn.NewMConnectionWithConfig
    0.50MB 0.015% 98.19%  3363.70MB 97.60%  github.com/cometbft/cometbft/p2p.newPeer
         0     0% 98.19%    19.21MB  0.56%  github.com/cometbft/cometbft/node.NewNode
         0     0% 98.19%  2239.52MB 64.98%  github.com/cometbft/cometbft/p2p.(*MultiplexTransport).Accept
         0     0% 98.19%  1124.68MB 32.63%  github.com/cometbft/cometbft/p2p.(*MultiplexTransport).Dial
         0     0% 98.19%  3363.70MB 97.60%  github.com/cometbft/cometbft/p2p.(*MultiplexTransport).wrapPeer
         0     0% 98.19%  1128.68MB 32.75%  github.com/cometbft/cometbft/p2p.(*Switch).DialPeerWithAddress
```

PS: we can provide access to `pprof` if requested

**Comment by cason** [comment]
Interesting. Do you have data for the number of inbound and outbound connections of the node during the reported period?

**Comment by cason** [comment]
Some context here. Nodes operating in seed mode maintain, this a general role, transient connection with peers.

The crawlPeers routine (right part of the picture), continually dial peer addresses present in the address book in order to request more peer address to that peer. This has also the effect of checking whether peer addresses in the address book are still valid, namely if they refer to reachable nodes. This results, of course in a high number of outbound peers, but there is also a routine, not represented in the picture that closes connections established in this way, as their point was to crawl the network, not to have long-term peers.

The left part of the figure refers to inbound peers, i.e., nodes from which the seed node accept connections. In this case, the connections should be even shorter. In fact, nodes dial a seed no in order to request peer addresses. Once the request is received and replied by the seed node, the inbound connection is immediately closed. The data you are presenting seems to indicate that this method is not working as expected.

**Comment by cason** [comment]
We have received several reports that running a seed node is very expensive in terms of used resources. In fact, we are considering to offer an alternative and simplified version of this feature, see https://github.com/cometbft/cometbft/issues/309.

**Comment by p4u** [comment]
> Interesting. Do you have data for the number of inbound and outbound connections of the node during the reported period?

Not much. This is a network of 6-8 nodes. `netstat` shows no connections established.

**Comment by cason** [comment]
I would like to understand better this issue.

Is the situation reported there only observed in seed nodes? If so, I think the title and description should be changed to reflect this specific. In this case, this issue should be hang on a higher level issue describing problems specific for seed nodes.

Being or not specific for seed nodes, it would be good to find a way to reproduced the reported issue in e2e tests, so that we can come up and validate possible solutions.

**Comment by p4u** [comment]
Tittle changed.

**Comment by p4u** [comment]
The cause is probably a goroutine that is not being properly finalized.

The following chart shows the seed node goroutines (green) in comparison with the rest of the network nodes (not seed).
![image](https://github.com/cometbft/cometbft/assets/1075446/15071408-f2e5-458a-ae7b-00591e6202ad)

**Comment by p4u** [comment]
Umm, suddenly the memory leak has disappeared. I'm not certain why.

It might be that some other of our components was creating a misbehavior for the seed p2p connection, or something in the network changed, making the leak disappear. 

We also yesterday upgraded to cometBFT 0.37.2 and the memory and everything works as expected.

Thus, I'm closing this issue and if we observe again the leak, I'll reopen it. 

Thanks for your efforts.

**Comment by cason** [comment]
Recall that to remove a peer all reactors have to process the `RemovePeer(Peer, reason)` p2p call. It can be possible that this part, at the protocol level, was leaking some threads. Thank you for the feedback.
