### ISSUE TITLE
Add Go API support to bootstrap node after it was state synced

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft#884]
### Context

The SDK recently added support to allow node operators to restore app state from a local snapshot (and additionally manipulate app snapshots).  For a more thorough context, see section "Application-implemented local state sync" from ADR 104 in #801.

As part of this work, the [`bootstrap-state`](https://github.com/cosmos/cosmos-sdk/pull/16061/files#diff-f946934088bd1a5b75846b7261731373d0b1f00ea507568ceb30fa8d624c6b4aR262) command in the SDK handles the bootstrapping of a fresh comet-based node. 

### Problem

This SDK `bootstrap-state` command comprises initializing the block store and state store, as well as light client verification. All of these steps rely on internal interfaces of CometBFT. 

### Proposal

Ideally, the SDK should be provided with a simpler and direct API from Comet that handles this bootstrapping functionality. We should add a public Go API method for this purpose.

**Comment by cason** [comment]
> This SDK bootstrap-state command comprises initializing the block store and state store, as well as light client verification

For the sake of precision, light client is used to retrieve the state for a given height, in the standard case the application's last height,  and the light-client obtained height is used to bootstrap the block store and the state store.

This same procedure is performed for a fresh node after running State Sync, check [here](https://github.com/cometbft/cometbft/blob/main/node/setup.go#L475), with the difference that the node proceed with its bootstrap by switching to Block Sync (this step is mandatory from v0.38).

**Comment by tac0turtle** [comment]
any chance the comet team can reopen this https://github.com/cometbft/cometbft/pull/803 and merge it? that would close this issue

**Comment by jmalicevic** [comment]
@tac0turtle , do you think having this merged into Comet would remove the need for the bootstrap command you have on your end and avoid having the state sync bootstrap code copied into the SDK?

**Comment by tac0turtle** [comment]
yea! we would wrap your command and delete the code we have

**Comment by jmalicevic** [comment]
Ok, thanks for the info then, we'll reopen the PR and take another look!

**Comment by jmalicevic** [comment]
As stated [here](https://github.com/cometbft/cometbft/pull/803#issuecomment-1614314892), we will indeed adopt the implementation from #803, but think it is safer to provide it as an API rather than a command for the cli. We'll take over the remaining work on transforming it and testing the API upon ourselves but it matches @yihuang 's original implementation with a few extra checks. As I can't edit the original branch, I had to create a new PR (#1505). 

Please let us know if you see any technical problems with the proposed API and if the API cannot support you for your use case. 

I am sorry it took so long to get back to you !
